// Code generated by 'yaegi extract github.com/yanlingrpa/protocol/browser'. DO NOT EDIT.

package symbols

import (
	"github.com/yanlingrpa/protocol/basic"
	"github.com/yanlingrpa/protocol/browser"
	"github.com/yanlingrpa/protocol/osgui"
	"github.com/yanlingrpa/protocol/ossys"
	"net/url"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/yanlingrpa/protocol/browser/browser"] = map[string]reflect.Value{
		// type definitions
		"BrowserElement":   reflect.ValueOf((*browser.BrowserElement)(nil)),
		"BrowserFramePage": reflect.ValueOf((*browser.BrowserFramePage)(nil)),
		"BrowserTabPage":   reflect.ValueOf((*browser.BrowserTabPage)(nil)),
		"BrowserWindow":    reflect.ValueOf((*browser.BrowserWindow)(nil)),

		// interface wrapper definitions
		"_BrowserElement":   reflect.ValueOf((*_github_com_yanlingrpa_protocol_browser_BrowserElement)(nil)),
		"_BrowserFramePage": reflect.ValueOf((*_github_com_yanlingrpa_protocol_browser_BrowserFramePage)(nil)),
		"_BrowserTabPage":   reflect.ValueOf((*_github_com_yanlingrpa_protocol_browser_BrowserTabPage)(nil)),
		"_BrowserWindow":    reflect.ValueOf((*_github_com_yanlingrpa_protocol_browser_BrowserWindow)(nil)),
	}
}

// _github_com_yanlingrpa_protocol_browser_BrowserElement is an interface wrapper for BrowserElement type
type _github_com_yanlingrpa_protocol_browser_BrowserElement struct {
	IValue            interface{}
	WBlur             func() error
	WClick            func() error
	WContainsElement  func(target browser.BrowserElement) (bool, error)
	WDisabled         func() (bool, error)
	WDoubleClick      func() error
	WEvalute          func(jsCode string, arg ...any) (any, error)
	WFocus            func()
	WFramePage        func() (browser.BrowserFramePage, error)
	WGetAttribute     func(name string) (string, error)
	WGetProperty      func(name string) (any, error)
	WGetXPath         func(optimized bool) (string, error)
	WHover            func() error
	WHtml             func() (string, error)
	WInput            func(text string) error
	WInteractable     func() (basic.FPoint, error)
	WMatchByCss       func(selector string) (bool, error)
	WMoveMouseOut     func() error
	WRightClick       func() error
	WScrollIntoView   func() error
	WSelectAllText    func() error
	WSelectByCss      func(selectors []string, selected bool) error
	WSelectByRegex    func(regexes []string, selected bool) error
	WSelectByText     func(texts []string, selected bool) error
	WSelectText       func(regex string) error
	WSetAttribute     func(name string, value string) error
	WSetFiles         func(filePaths []string) error
	WSetProperty      func(name string, value any) error
	WTap              func() error
	WText             func() (string, error)
	WVisible          func() (bool, error)
	WWaitEnabled      func() error
	WWaitInteractable func() (basic.FPoint, error)
	WWaitInvisible    func() error
	WWaitStable       func(stableTime time.Duration) error
	WWaitStableRAF    func() error
	WWaitVisible      func() error
	WWaitWritable     func() error
}

func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Blur() error {
	return W.WBlur()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Click() error {
	return W.WClick()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) ContainsElement(target browser.BrowserElement) (bool, error) {
	return W.WContainsElement(target)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Disabled() (bool, error) {
	return W.WDisabled()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) DoubleClick() error {
	return W.WDoubleClick()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Evalute(jsCode string, arg ...any) (any, error) {
	return W.WEvalute(jsCode, arg...)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Focus() {
	W.WFocus()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) FramePage() (browser.BrowserFramePage, error) {
	return W.WFramePage()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) GetAttribute(name string) (string, error) {
	return W.WGetAttribute(name)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) GetProperty(name string) (any, error) {
	return W.WGetProperty(name)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) GetXPath(optimized bool) (string, error) {
	return W.WGetXPath(optimized)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Hover() error {
	return W.WHover()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Html() (string, error) {
	return W.WHtml()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Input(text string) error {
	return W.WInput(text)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Interactable() (basic.FPoint, error) {
	return W.WInteractable()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) MatchByCss(selector string) (bool, error) {
	return W.WMatchByCss(selector)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) MoveMouseOut() error {
	return W.WMoveMouseOut()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) RightClick() error {
	return W.WRightClick()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) ScrollIntoView() error {
	return W.WScrollIntoView()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SelectAllText() error {
	return W.WSelectAllText()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SelectByCss(selectors []string, selected bool) error {
	return W.WSelectByCss(selectors, selected)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SelectByRegex(regexes []string, selected bool) error {
	return W.WSelectByRegex(regexes, selected)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SelectByText(texts []string, selected bool) error {
	return W.WSelectByText(texts, selected)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SelectText(regex string) error {
	return W.WSelectText(regex)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SetAttribute(name string, value string) error {
	return W.WSetAttribute(name, value)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SetFiles(filePaths []string) error {
	return W.WSetFiles(filePaths)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) SetProperty(name string, value any) error {
	return W.WSetProperty(name, value)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Tap() error {
	return W.WTap()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Text() (string, error) {
	return W.WText()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) Visible() (bool, error) {
	return W.WVisible()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) WaitEnabled() error {
	return W.WWaitEnabled()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) WaitInteractable() (basic.FPoint, error) {
	return W.WWaitInteractable()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) WaitInvisible() error {
	return W.WWaitInvisible()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) WaitStable(stableTime time.Duration) error {
	return W.WWaitStable(stableTime)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) WaitStableRAF() error {
	return W.WWaitStableRAF()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) WaitVisible() error {
	return W.WWaitVisible()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserElement) WaitWritable() error {
	return W.WWaitWritable()
}

// _github_com_yanlingrpa_protocol_browser_BrowserFramePage is an interface wrapper for BrowserFramePage type
type _github_com_yanlingrpa_protocol_browser_BrowserFramePage struct {
	IValue            interface{}
	WEvaluate         func(jsCode string, arg ...any) (any, error)
	WGetDomain        func() string
	WGetID            func() string
	WGetTitle         func() string
	WGetURL           func() *url.URL
	WIsFrame          func() bool
	WQuerySelector    func(selector string, timeout time.Duration) (browser.BrowserElement, error)
	WQuerySelectorAll func(selector string, timeout time.Duration) ([]browser.BrowserElement, error)
	WQueryXPath       func(xpath string, timeout time.Duration) (browser.BrowserElement, error)
	WQueryXPathAll    func(xpath string, timeout time.Duration) ([]browser.BrowserElement, error)
	WReload           func(timeout time.Duration) error
	WWaitSelector     func(selector string, timeout time.Duration) (browser.BrowserElement, error)
}

func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) Evaluate(jsCode string, arg ...any) (any, error) {
	return W.WEvaluate(jsCode, arg...)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) GetDomain() string {
	return W.WGetDomain()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) GetID() string {
	return W.WGetID()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) GetTitle() string {
	return W.WGetTitle()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) GetURL() *url.URL {
	return W.WGetURL()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) IsFrame() bool {
	return W.WIsFrame()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) QuerySelector(selector string, timeout time.Duration) (browser.BrowserElement, error) {
	return W.WQuerySelector(selector, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) QuerySelectorAll(selector string, timeout time.Duration) ([]browser.BrowserElement, error) {
	return W.WQuerySelectorAll(selector, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) QueryXPath(xpath string, timeout time.Duration) (browser.BrowserElement, error) {
	return W.WQueryXPath(xpath, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) QueryXPathAll(xpath string, timeout time.Duration) ([]browser.BrowserElement, error) {
	return W.WQueryXPathAll(xpath, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) Reload(timeout time.Duration) error {
	return W.WReload(timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserFramePage) WaitSelector(selector string, timeout time.Duration) (browser.BrowserElement, error) {
	return W.WWaitSelector(selector, timeout)
}

// _github_com_yanlingrpa_protocol_browser_BrowserTabPage is an interface wrapper for BrowserTabPage type
type _github_com_yanlingrpa_protocol_browser_BrowserTabPage struct {
	IValue                interface{}
	WActivate             func() error
	WClearAllIndexDBFiles func() error
	WClearCookies         func() error
	WClearLocalStorage    func() error
	WDestroy              func() error
	WEvaluate             func(jsCode string, arg ...any) (any, error)
	WGetDomain            func() string
	WGetID                func() string
	WGetTitle             func() string
	WGetURL               func() *url.URL
	WIsFrame              func() bool
	WLoadCookies          func() error
	WLoadLocalStorage     func() error
	WQuerySelector        func(selector string, timeout time.Duration) (browser.BrowserElement, error)
	WQuerySelectorAll     func(selector string, timeout time.Duration) ([]browser.BrowserElement, error)
	WQueryXPath           func(xpath string, timeout time.Duration) (browser.BrowserElement, error)
	WQueryXPathAll        func(xpath string, timeout time.Duration) ([]browser.BrowserElement, error)
	WReload               func(timeout time.Duration) error
	WSaveCookies          func() error
	WSaveLocalStorage     func() error
	WWaitForNewTab        func(id string, timeout time.Duration) error
	WWaitSelector         func(selector string, timeout time.Duration) (browser.BrowserElement, error)
}

func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) Activate() error {
	return W.WActivate()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) ClearAllIndexDBFiles() error {
	return W.WClearAllIndexDBFiles()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) ClearCookies() error {
	return W.WClearCookies()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) ClearLocalStorage() error {
	return W.WClearLocalStorage()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) Destroy() error {
	return W.WDestroy()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) Evaluate(jsCode string, arg ...any) (any, error) {
	return W.WEvaluate(jsCode, arg...)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) GetDomain() string {
	return W.WGetDomain()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) GetID() string {
	return W.WGetID()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) GetTitle() string {
	return W.WGetTitle()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) GetURL() *url.URL {
	return W.WGetURL()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) IsFrame() bool {
	return W.WIsFrame()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) LoadCookies() error {
	return W.WLoadCookies()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) LoadLocalStorage() error {
	return W.WLoadLocalStorage()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) QuerySelector(selector string, timeout time.Duration) (browser.BrowserElement, error) {
	return W.WQuerySelector(selector, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) QuerySelectorAll(selector string, timeout time.Duration) ([]browser.BrowserElement, error) {
	return W.WQuerySelectorAll(selector, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) QueryXPath(xpath string, timeout time.Duration) (browser.BrowserElement, error) {
	return W.WQueryXPath(xpath, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) QueryXPathAll(xpath string, timeout time.Duration) ([]browser.BrowserElement, error) {
	return W.WQueryXPathAll(xpath, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) Reload(timeout time.Duration) error {
	return W.WReload(timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) SaveCookies() error {
	return W.WSaveCookies()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) SaveLocalStorage() error {
	return W.WSaveLocalStorage()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) WaitForNewTab(id string, timeout time.Duration) error {
	return W.WWaitForNewTab(id, timeout)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserTabPage) WaitSelector(selector string, timeout time.Duration) (browser.BrowserElement, error) {
	return W.WWaitSelector(selector, timeout)
}

// _github_com_yanlingrpa_protocol_browser_BrowserWindow is an interface wrapper for BrowserWindow type
type _github_com_yanlingrpa_protocol_browser_BrowserWindow struct {
	IValue              interface{}
	WActivate           func() (bool, error)
	WBodyLocator        func() (osgui.Locator, error)
	WClose              func() error
	WCurrentPage        func() browser.BrowserTabPage
	WDeActivate         func() (bool, error)
	WDefaultPage        func() browser.BrowserTabPage
	WGetClientRect      func() basic.Rect
	WGetHwnd            func() uintptr
	WGetID              func() string
	WGetInitiatorPath   func() string
	WGetMonitor         func() ossys.MonitorInfo
	WGetWindowCaretPos  func() *basic.Point
	WGetWindowCursorPos func() *basic.Point
	WGetWindowRect      func() basic.Rect
	WGetWindowSchema    func() string
	WGetWindowTitle     func() string
	WIDTabPage          func() browser.BrowserTabPage
	WMoveTo             func(global_x int, global_y int) (bool, error)
	WNewTabPage         func(id string, url string) (browser.BrowserTabPage, error)
	WPressKeys          func(keys ...osgui.Keyboard) error
	WReadClipboard      func() (string, error)
	WRectLocator        func(rect basic.Rect) (osgui.Locator, error)
	WResizeTo           func(width int, height int) (bool, error)
	WSnapshot           func(gray bool) ([]byte, error)
	WToMap              func() map[string]any
	WTransFromScreen    func(screen_pos *basic.Point) *basic.Point
	WTransToScreen      func(window_pos *basic.Point) *basic.Point
	WWriteClipboard     func(text string) error
}

func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) Activate() (bool, error) {
	return W.WActivate()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) BodyLocator() (osgui.Locator, error) {
	return W.WBodyLocator()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) Close() error {
	return W.WClose()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) CurrentPage() browser.BrowserTabPage {
	return W.WCurrentPage()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) DeActivate() (bool, error) {
	return W.WDeActivate()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) DefaultPage() browser.BrowserTabPage {
	return W.WDefaultPage()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetClientRect() basic.Rect {
	return W.WGetClientRect()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetHwnd() uintptr {
	return W.WGetHwnd()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetID() string {
	return W.WGetID()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetInitiatorPath() string {
	return W.WGetInitiatorPath()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetMonitor() ossys.MonitorInfo {
	return W.WGetMonitor()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetWindowCaretPos() *basic.Point {
	return W.WGetWindowCaretPos()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetWindowCursorPos() *basic.Point {
	return W.WGetWindowCursorPos()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetWindowRect() basic.Rect {
	return W.WGetWindowRect()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetWindowSchema() string {
	return W.WGetWindowSchema()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) GetWindowTitle() string {
	return W.WGetWindowTitle()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) IDTabPage() browser.BrowserTabPage {
	return W.WIDTabPage()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) MoveTo(global_x int, global_y int) (bool, error) {
	return W.WMoveTo(global_x, global_y)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) NewTabPage(id string, url string) (browser.BrowserTabPage, error) {
	return W.WNewTabPage(id, url)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) PressKeys(keys ...osgui.Keyboard) error {
	return W.WPressKeys(keys...)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) ReadClipboard() (string, error) {
	return W.WReadClipboard()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) RectLocator(rect basic.Rect) (osgui.Locator, error) {
	return W.WRectLocator(rect)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) ResizeTo(width int, height int) (bool, error) {
	return W.WResizeTo(width, height)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) Snapshot(gray bool) ([]byte, error) {
	return W.WSnapshot(gray)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) ToMap() map[string]any {
	return W.WToMap()
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) TransFromScreen(screen_pos *basic.Point) *basic.Point {
	return W.WTransFromScreen(screen_pos)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) TransToScreen(window_pos *basic.Point) *basic.Point {
	return W.WTransToScreen(window_pos)
}
func (W _github_com_yanlingrpa_protocol_browser_BrowserWindow) WriteClipboard(text string) error {
	return W.WWriteClipboard(text)
}
