// Code generated by 'yaegi extract github.com/yanlingrpa/protocol/extention'. DO NOT EDIT.

package symbols

import (
	"github.com/yanlingrpa/protocol/extention"
	"reflect"
)

func init() {
	Symbols["github.com/yanlingrpa/protocol/extention/extention"] = map[string]reflect.Value{
		// type definitions
		"OcrResult":       reflect.ValueOf((*extention.OcrResult)(nil)),
		"OcrWord":         reflect.ValueOf((*extention.OcrWord)(nil)),
		"VisionExtension": reflect.ValueOf((*extention.VisionExtension)(nil)),

		// interface wrapper definitions
		"_VisionExtension": reflect.ValueOf((*_github_com_yanlingrpa_protocol_extention_VisionExtension)(nil)),
	}
}

// _github_com_yanlingrpa_protocol_extention_VisionExtension is an interface wrapper for VisionExtension type
type _github_com_yanlingrpa_protocol_extention_VisionExtension struct {
	IValue       interface{}
	WImageDetect func(image []byte, prompt string, question string) (string, error)
	WImageOcr    func(image []byte) (*extention.OcrResult, error)
	WImageRead   func(image []byte, prompt string, question string) (string, error)
}

func (W _github_com_yanlingrpa_protocol_extention_VisionExtension) ImageDetect(image []byte, prompt string, question string) (string, error) {
	return W.WImageDetect(image, prompt, question)
}
func (W _github_com_yanlingrpa_protocol_extention_VisionExtension) ImageOcr(image []byte) (*extention.OcrResult, error) {
	return W.WImageOcr(image)
}
func (W _github_com_yanlingrpa_protocol_extention_VisionExtension) ImageRead(image []byte, prompt string, question string) (string, error) {
	return W.WImageRead(image, prompt, question)
}
