// Code generated by 'yaegi extract github.com/yanlingrpa/protocol/extention'. DO NOT EDIT.

package symbols

import (
	"github.com/yanlingrpa/protocol/basic"
	"github.com/yanlingrpa/protocol/extention"
	"reflect"
)

func init() {
	Symbols["github.com/yanlingrpa/protocol/extention/extention"] = map[string]reflect.Value{
		// type definitions
		"OcrResult":       reflect.ValueOf((*extention.OcrResult)(nil)),
		"OcrWord":         reflect.ValueOf((*extention.OcrWord)(nil)),
		"VisionExtension": reflect.ValueOf((*extention.VisionExtension)(nil)),

		// interface wrapper definitions
		"_VisionExtension": reflect.ValueOf((*_github_com_yanlingrpa_protocol_extention_VisionExtension)(nil)),
	}
}

// _github_com_yanlingrpa_protocol_extention_VisionExtension is an interface wrapper for VisionExtension type
type _github_com_yanlingrpa_protocol_extention_VisionExtension struct {
	IValue  interface{}
	WDetect func(image []byte, prompt string, question string) (string, error)
	WLocate func(image []byte, text string) ([]basic.Rect, error)
	WOcr    func(image []byte) (*extention.OcrResult, error)
	WRead   func(image []byte, prompt string, question string) (string, error)
}

func (W _github_com_yanlingrpa_protocol_extention_VisionExtension) Detect(image []byte, prompt string, question string) (string, error) {
	return W.WDetect(image, prompt, question)
}
func (W _github_com_yanlingrpa_protocol_extention_VisionExtension) Locate(image []byte, text string) ([]basic.Rect, error) {
	return W.WLocate(image, text)
}
func (W _github_com_yanlingrpa_protocol_extention_VisionExtension) Ocr(image []byte) (*extention.OcrResult, error) {
	return W.WOcr(image)
}
func (W _github_com_yanlingrpa_protocol_extention_VisionExtension) Read(image []byte, prompt string, question string) (string, error) {
	return W.WRead(image, prompt, question)
}
