// Code generated by 'yaegi extract github.com/yanlingrpa/protocol/script'. DO NOT EDIT.

package symbols

import (
	"reflect"

	"github.com/yanlingrpa/protocol/browser"
	"github.com/yanlingrpa/protocol/osgui"
	"github.com/yanlingrpa/protocol/ossys"
	"github.com/yanlingrpa/protocol/script"
)

func init() {
	Symbols["github.com/yanlingrpa/protocol/script/script"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ParseSpecifier":   reflect.ValueOf(script.ParseSpecifier),
		"VariableBoolean":  reflect.ValueOf(script.VariableBoolean),
		"VariableFilePath": reflect.ValueOf(script.VariableFilePath),
		"VariableInteger":  reflect.ValueOf(script.VariableInteger),
		"VariableJson":     reflect.ValueOf(script.VariableJson),
		"VariableNumber":   reflect.ValueOf(script.VariableNumber),
		"VariableString":   reflect.ValueOf(script.VariableString),

		// type definitions
		"ApiParameter":     reflect.ValueOf((*script.ApiParameter)(nil)),
		"Event":            reflect.ValueOf((*script.Event)(nil)),
		"EventHandler":     reflect.ValueOf((*script.EventHandler)(nil)),
		"ExportApi":        reflect.ValueOf((*script.ExportApi)(nil)),
		"ExportTopic":      reflect.ValueOf((*script.ExportTopic)(nil)),
		"GuiApplication":   reflect.ValueOf((*script.GuiApplication)(nil)),
		"ModuleInfo":       reflect.ValueOf((*script.ModuleInfo)(nil)),
		"ModuleRuntime":    reflect.ValueOf((*script.ModuleRuntime)(nil)),
		"ScriptVariable":   reflect.ValueOf((*script.ScriptVariable)(nil)),
		"Specifier":        reflect.ValueOf((*script.Specifier)(nil)),
		"Subscriber":       reflect.ValueOf((*script.Subscriber)(nil)),
		"UrlPermission":    reflect.ValueOf((*script.UrlPermission)(nil)),
		"VariableDataType": reflect.ValueOf((*script.VariableDataType)(nil)),
		"WebApplication":   reflect.ValueOf((*script.WebApplication)(nil)),
		"YanLingScript":    reflect.ValueOf((*script.YanLingScript)(nil)),

		// interface wrapper definitions
		"_ModuleRuntime": reflect.ValueOf((*_github_com_yanling_rpa_protocol_script_ModuleRuntime)(nil)),
		"_Subscriber":    reflect.ValueOf((*_github_com_yanling_rpa_protocol_script_Subscriber)(nil)),
	}
}

// _github_com_yanling_rpa_protocol_script_ModuleRuntime is an interface wrapper for ModuleRuntime type
type _github_com_yanling_rpa_protocol_script_ModuleRuntime struct {
	IValue            interface{}
	WBrowserWindow    func(id string) (browser.BrowserWindow, bool)
	WCurrentSpecifier func() string
	WDeviceInfo       func() ossys.DeviceInfo
	WFileSystem       func() ossys.LocalFilesystem
	WGetCacheData     func(key string) (any, bool)
	WGetVariable      func(name string) (any, bool)
	WGuiWindow        func(id string) (osgui.GuiWindow, bool)
	WHostSpecifier    func() string
	WHttpClient       func() ossys.HttpClient
	WInvokeApi        func(specifier string, api string, args ...any) (any, error)
	WLogger           func() ossys.ScriptLogger
	WSetCacheData     func(key string, value any)
	WStorage          func() ossys.LocalStorage
	WSubscribe        func(specifier string, topic string, handler script.EventHandler) (script.Subscriber, error)
	WUnsubscribe      func(subscriber script.Subscriber) error
}

func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) BrowserWindow(id string) (browser.BrowserWindow, bool) {
	return W.WBrowserWindow(id)
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) CurrentSpecifier() string {
	return W.WCurrentSpecifier()
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) DeviceInfo() ossys.DeviceInfo {
	return W.WDeviceInfo()
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) FileSystem() ossys.LocalFilesystem {
	return W.WFileSystem()
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) GetCacheData(key string) (any, bool) {
	return W.WGetCacheData(key)
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) GetVariable(name string) (any, bool) {
	return W.WGetVariable(name)
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) GuiWindow(id string) (osgui.GuiWindow, bool) {
	return W.WGuiWindow(id)
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) HostSpecifier() string {
	return W.WHostSpecifier()
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) HttpClient() ossys.HttpClient {
	return W.WHttpClient()
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) InvokeApi(specifier string, api string, args ...any) (any, error) {
	return W.WInvokeApi(specifier, api, args...)
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) Logger() ossys.ScriptLogger {
	return W.WLogger()
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) SetCacheData(key string, value any) {
	W.WSetCacheData(key, value)
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) Storage() ossys.LocalStorage {
	return W.WStorage()
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) Subscribe(specifier string, topic string, handler script.EventHandler) (script.Subscriber, error) {
	return W.WSubscribe(specifier, topic, handler)
}
func (W _github_com_yanling_rpa_protocol_script_ModuleRuntime) Unsubscribe(subscriber script.Subscriber) error {
	return W.WUnsubscribe(subscriber)
}

// _github_com_yanling_rpa_protocol_script_Subscriber is an interface wrapper for Subscriber type
type _github_com_yanling_rpa_protocol_script_Subscriber struct {
	IValue        interface{}
	WGetSpecifier func() string
	WGetTopic     func() string
	WIsActive     func() bool
}

func (W _github_com_yanling_rpa_protocol_script_Subscriber) GetSpecifier() string {
	return W.WGetSpecifier()
}
func (W _github_com_yanling_rpa_protocol_script_Subscriber) GetTopic() string {
	return W.WGetTopic()
}
func (W _github_com_yanling_rpa_protocol_script_Subscriber) IsActive() bool {
	return W.WIsActive()
}
