// Code generated by 'yaegi extract path/filepath'. DO NOT EDIT.

//go:build go1.25
// +build go1.25

package symbols

import (
	"go/constant"
	"go/token"
	"path/filepath"
	"reflect"
)

func init() {
	Symbols["path/filepath/filepath"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Base":          reflect.ValueOf(filepath.Base),
		"Clean":         reflect.ValueOf(filepath.Clean),
		"Dir":           reflect.ValueOf(filepath.Dir),
		"ErrBadPattern": reflect.ValueOf(&filepath.ErrBadPattern).Elem(),
		"Ext":           reflect.ValueOf(filepath.Ext),
		"FromSlash":     reflect.ValueOf(filepath.FromSlash),
		"HasPrefix":     reflect.ValueOf(filepath.HasPrefix),
		"IsAbs":         reflect.ValueOf(filepath.IsAbs),
		"IsLocal":       reflect.ValueOf(filepath.IsLocal),
		"Join":          reflect.ValueOf(filepath.Join),
		"ListSeparator": reflect.ValueOf(constant.MakeFromLiteral("59", token.INT, 0)),
		"Localize":      reflect.ValueOf(filepath.Localize),
		"Match":         reflect.ValueOf(filepath.Match),
		"Rel":           reflect.ValueOf(filepath.Rel),
		"Separator":     reflect.ValueOf(constant.MakeFromLiteral("92", token.INT, 0)),
		"SkipAll":       reflect.ValueOf(&filepath.SkipAll).Elem(),
		"SkipDir":       reflect.ValueOf(&filepath.SkipDir).Elem(),
		"Split":         reflect.ValueOf(filepath.Split),
		"SplitList":     reflect.ValueOf(filepath.SplitList),
		"ToSlash":       reflect.ValueOf(filepath.ToSlash),
		"VolumeName":    reflect.ValueOf(filepath.VolumeName),
	}
}
