// Code generated by 'yaegi extract yanlingrpa.com/yanling/protocol/appgui'. DO NOT EDIT.

package symbols

import (
	"reflect"
	"time"
	"yanlingrpa.com/yanling/protocol/appgui"
	"yanlingrpa.com/yanling/protocol/basic"
)

func init() {
	Symbols["yanlingrpa.com/yanling/protocol/appgui/appgui"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"KeyBack":       reflect.ValueOf(appgui.KeyBack),
		"KeyBackspace":  reflect.ValueOf(appgui.KeyBackspace),
		"KeyDelete":     reflect.ValueOf(appgui.KeyDelete),
		"KeyDone":       reflect.ValueOf(appgui.KeyDone),
		"KeyEnter":      reflect.ValueOf(appgui.KeyEnter),
		"KeyHome":       reflect.ValueOf(appgui.KeyHome),
		"KeyMenu":       reflect.ValueOf(appgui.KeyMenu),
		"KeyNext":       reflect.ValueOf(appgui.KeyNext),
		"KeyPower":      reflect.ValueOf(appgui.KeyPower),
		"KeyPrevious":   reflect.ValueOf(appgui.KeyPrevious),
		"KeyRecent":     reflect.ValueOf(appgui.KeyRecent),
		"KeySearch":     reflect.ValueOf(appgui.KeySearch),
		"KeySpace":      reflect.ValueOf(appgui.KeySpace),
		"KeyTab":        reflect.ValueOf(appgui.KeyTab),
		"KeyVolumeDown": reflect.ValueOf(appgui.KeyVolumeDown),
		"KeyVolumeMute": reflect.ValueOf(appgui.KeyVolumeMute),
		"KeyVolumeUp":   reflect.ValueOf(appgui.KeyVolumeUp),

		// type definitions
		"AppGuiLocator": reflect.ValueOf((*appgui.AppGuiLocator)(nil)),
		"AppGuiWindow":  reflect.ValueOf((*appgui.AppGuiWindow)(nil)),
		"AppKey":        reflect.ValueOf((*appgui.AppKey)(nil)),

		// interface wrapper definitions
		"_AppGuiLocator": reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator)(nil)),
		"_AppGuiWindow":  reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow)(nil)),
	}
}

// _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator is an interface wrapper for AppGuiLocator type
type _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator struct {
	IValue               interface{}
	WCanScrollHorizontal func() bool
	WCanScrollVertical   func() bool
	WCardLocator         func(min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error)
	WClearText           func() error
	WDoubleTap           func(locator_point *basic.Point) error
	WFocus               func() error
	WGetBodyRect         func() basic.Rect
	WGetLocatorTouchPos  func() *basic.Point
	WGetScreenRect       func() basic.Rect
	WGetSize             func() basic.Size
	WGetWindowRect       func() basic.Rect
	WImageLocator        func(image string, sim float32) ([]appgui.AppGuiLocator, error)
	WIsEditing           func() bool
	WLongPress           func(locator_point *basic.Point) error
	WOcrRead             func(confidence float64) (*basic.OcrResult, error)
	WPinch               func(spread bool, scale float32) error
	WPressKeys           func(keys ...appgui.AppKey) error
	WReadText            func() (string, error)
	WScrollHorizontal    func(forward bool, distance int) error
	WScrollVertical      func(forward bool, distance int) error
	WSnapshot            func(gray bool) ([]byte, error)
	WSubLocator          func(locator_point basic.Point, size basic.Size) appgui.AppGuiLocator
	WSwipeTo             func(from_locator_point *basic.Point, to_locator_point *basic.Point) error
	WTap                 func(locator_point *basic.Point) error
	WTextLocator         func(texts ...string) ([]appgui.AppGuiLocator, error)
	WToMap               func() map[string]any
	WTouchDown           func() error
	WTouchMove           func(locator_point *basic.Point) error
	WTouchUp             func() error
	WTransFromBody       func(body_pos *basic.Point) *basic.Point
	WTransFromScreen     func(screen_pos *basic.Point) *basic.Point
	WTransFromWindow     func(window_pos *basic.Point) *basic.Point
	WTransToBody         func(locator_point *basic.Point) *basic.Point
	WTransToScreen       func(locator_point *basic.Point) *basic.Point
	WTransToWindow       func(locator_point *basic.Point) *basic.Point
	WVisionLocator       func(description string, min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error)
	WWaitForCard         func(timeout time.Duration, min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error)
	WWaitForEditing      func(timeout time.Duration) (appgui.AppGuiLocator, error)
	WWaitForImage        func(timeout time.Duration, image string, sim float32) ([]appgui.AppGuiLocator, error)
	WWaitForText         func(timeout time.Duration, texts ...string) ([]appgui.AppGuiLocator, error)
	WWaitForVision       func(timeout time.Duration, description string, min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error)
	WWriteText           func(text string) error
}

func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) CanScrollHorizontal() bool {
	return W.WCanScrollHorizontal()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) CanScrollVertical() bool {
	return W.WCanScrollVertical()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) CardLocator(min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error) {
	return W.WCardLocator(min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) ClearText() error {
	return W.WClearText()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) DoubleTap(locator_point *basic.Point) error {
	return W.WDoubleTap(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) Focus() error {
	return W.WFocus()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) GetBodyRect() basic.Rect {
	return W.WGetBodyRect()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) GetLocatorTouchPos() *basic.Point {
	return W.WGetLocatorTouchPos()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) GetScreenRect() basic.Rect {
	return W.WGetScreenRect()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) GetSize() basic.Size {
	return W.WGetSize()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) GetWindowRect() basic.Rect {
	return W.WGetWindowRect()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) ImageLocator(image string, sim float32) ([]appgui.AppGuiLocator, error) {
	return W.WImageLocator(image, sim)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) IsEditing() bool {
	return W.WIsEditing()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) LongPress(locator_point *basic.Point) error {
	return W.WLongPress(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) OcrRead(confidence float64) (*basic.OcrResult, error) {
	return W.WOcrRead(confidence)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) Pinch(spread bool, scale float32) error {
	return W.WPinch(spread, scale)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) PressKeys(keys ...appgui.AppKey) error {
	return W.WPressKeys(keys...)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) ReadText() (string, error) {
	return W.WReadText()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) ScrollHorizontal(forward bool, distance int) error {
	return W.WScrollHorizontal(forward, distance)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) ScrollVertical(forward bool, distance int) error {
	return W.WScrollVertical(forward, distance)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) Snapshot(gray bool) ([]byte, error) {
	return W.WSnapshot(gray)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) SubLocator(locator_point basic.Point, size basic.Size) appgui.AppGuiLocator {
	return W.WSubLocator(locator_point, size)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) SwipeTo(from_locator_point *basic.Point, to_locator_point *basic.Point) error {
	return W.WSwipeTo(from_locator_point, to_locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) Tap(locator_point *basic.Point) error {
	return W.WTap(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TextLocator(texts ...string) ([]appgui.AppGuiLocator, error) {
	return W.WTextLocator(texts...)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) ToMap() map[string]any {
	return W.WToMap()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TouchDown() error {
	return W.WTouchDown()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TouchMove(locator_point *basic.Point) error {
	return W.WTouchMove(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TouchUp() error {
	return W.WTouchUp()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TransFromBody(body_pos *basic.Point) *basic.Point {
	return W.WTransFromBody(body_pos)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TransFromScreen(screen_pos *basic.Point) *basic.Point {
	return W.WTransFromScreen(screen_pos)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TransFromWindow(window_pos *basic.Point) *basic.Point {
	return W.WTransFromWindow(window_pos)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TransToBody(locator_point *basic.Point) *basic.Point {
	return W.WTransToBody(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TransToScreen(locator_point *basic.Point) *basic.Point {
	return W.WTransToScreen(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) TransToWindow(locator_point *basic.Point) *basic.Point {
	return W.WTransToWindow(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) VisionLocator(description string, min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error) {
	return W.WVisionLocator(description, min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) WaitForCard(timeout time.Duration, min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error) {
	return W.WWaitForCard(timeout, min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) WaitForEditing(timeout time.Duration) (appgui.AppGuiLocator, error) {
	return W.WWaitForEditing(timeout)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) WaitForImage(timeout time.Duration, image string, sim float32) ([]appgui.AppGuiLocator, error) {
	return W.WWaitForImage(timeout, image, sim)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) WaitForText(timeout time.Duration, texts ...string) ([]appgui.AppGuiLocator, error) {
	return W.WWaitForText(timeout, texts...)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) WaitForVision(timeout time.Duration, description string, min_size *basic.Size, max_size *basic.Size) ([]appgui.AppGuiLocator, error) {
	return W.WWaitForVision(timeout, description, min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiLocator) WriteText(text string) error {
	return W.WWriteText(text)
}

// _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow is an interface wrapper for AppGuiWindow type
type _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow struct {
	IValue             interface{}
	WActivate          func() (bool, error)
	WBodyLocator       func() (appgui.AppGuiLocator, error)
	WClose             func() error
	WDeActivate        func() (bool, error)
	WGetAppActivity    func() string
	WGetAppPackage     func() string
	WGetClientRect     func() basic.Rect
	WGetID             func() string
	WGetScreenRect     func() basic.Rect
	WGetWindowTitle    func() string
	WGetWindowTouchPos func() *basic.Point
	WPressKey          func(key appgui.AppKey) error
	WReadClipboard     func() (string, error)
	WRectLocator       func(rect basic.Rect) (appgui.AppGuiLocator, error)
	WSnapshot          func(gray bool) ([]byte, error)
	WToMap             func() map[string]any
	WTransFromScreen   func(screen_pos *basic.Point) *basic.Point
	WTransToScreen     func(window_pos *basic.Point) *basic.Point
	WWriteClipboard    func(text string) error
}

func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) Activate() (bool, error) {
	return W.WActivate()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) BodyLocator() (appgui.AppGuiLocator, error) {
	return W.WBodyLocator()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) Close() error {
	return W.WClose()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) DeActivate() (bool, error) {
	return W.WDeActivate()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) GetAppActivity() string {
	return W.WGetAppActivity()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) GetAppPackage() string {
	return W.WGetAppPackage()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) GetClientRect() basic.Rect {
	return W.WGetClientRect()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) GetID() string {
	return W.WGetID()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) GetScreenRect() basic.Rect {
	return W.WGetScreenRect()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) GetWindowTitle() string {
	return W.WGetWindowTitle()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) GetWindowTouchPos() *basic.Point {
	return W.WGetWindowTouchPos()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) PressKey(key appgui.AppKey) error {
	return W.WPressKey(key)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) ReadClipboard() (string, error) {
	return W.WReadClipboard()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) RectLocator(rect basic.Rect) (appgui.AppGuiLocator, error) {
	return W.WRectLocator(rect)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) Snapshot(gray bool) ([]byte, error) {
	return W.WSnapshot(gray)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) ToMap() map[string]any {
	return W.WToMap()
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) TransFromScreen(screen_pos *basic.Point) *basic.Point {
	return W.WTransFromScreen(screen_pos)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) TransToScreen(window_pos *basic.Point) *basic.Point {
	return W.WTransToScreen(window_pos)
}
func (W _yanlingrpa_com_yanling_protocol_appgui_AppGuiWindow) WriteClipboard(text string) error {
	return W.WWriteClipboard(text)
}
