// Code generated by 'yaegi extract yanlingrpa.com/yanling/protocol/component'. DO NOT EDIT.

package symbols

import (
	"reflect"
	"yanlingrpa.com/yanling/protocol/basic"
	"yanlingrpa.com/yanling/protocol/component"
)

func init() {
	Symbols["yanlingrpa.com/yanling/protocol/component/component"] = map[string]reflect.Value{
		// type definitions
		"OcrWorker":    reflect.ValueOf((*component.OcrWorker)(nil)),
		"VisionWorker": reflect.ValueOf((*component.VisionWorker)(nil)),

		// interface wrapper definitions
		"_OcrWorker":    reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_component_OcrWorker)(nil)),
		"_VisionWorker": reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_component_VisionWorker)(nil)),
	}
}

// _yanlingrpa_com_yanling_protocol_component_OcrWorker is an interface wrapper for OcrWorker type
type _yanlingrpa_com_yanling_protocol_component_OcrWorker struct {
	IValue    interface{}
	WOcrImage func(image []byte) (*basic.OcrResult, error)
}

func (W _yanlingrpa_com_yanling_protocol_component_OcrWorker) OcrImage(image []byte) (*basic.OcrResult, error) {
	return W.WOcrImage(image)
}

// _yanlingrpa_com_yanling_protocol_component_VisionWorker is an interface wrapper for VisionWorker type
type _yanlingrpa_com_yanling_protocol_component_VisionWorker struct {
	IValue  interface{}
	WDetect func(image []byte, instruction string, schema string) (string, error)
	WLocate func(image []byte, texts ...string) ([]basic.Rect, error)
	WOcr    func(image []byte) (*basic.OcrResult, error)
	WRead   func(image []byte, instruction string, schema string) (string, error)
}

func (W _yanlingrpa_com_yanling_protocol_component_VisionWorker) Detect(image []byte, instruction string, schema string) (string, error) {
	return W.WDetect(image, instruction, schema)
}
func (W _yanlingrpa_com_yanling_protocol_component_VisionWorker) Locate(image []byte, texts ...string) ([]basic.Rect, error) {
	return W.WLocate(image, texts...)
}
func (W _yanlingrpa_com_yanling_protocol_component_VisionWorker) Ocr(image []byte) (*basic.OcrResult, error) {
	return W.WOcr(image)
}
func (W _yanlingrpa_com_yanling_protocol_component_VisionWorker) Read(image []byte, instruction string, schema string) (string, error) {
	return W.WRead(image, instruction, schema)
}
