// Code generated by 'yaegi extract yanlingrpa.com/yanling/protocol/basic'. DO NOT EDIT.

package symbols

import (
	"reflect"
	"yanlingrpa.com/yanling/protocol/basic"
)

func init() {
	Symbols["yanlingrpa.com/yanling/protocol/basic/basic"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"MaxAreaRect":                reflect.ValueOf(basic.MaxAreaRect),
		"MergeAllRectangles":         reflect.ValueOf(basic.MergeAllRectangles),
		"MergeGroupRectangles":       reflect.ValueOf(basic.MergeGroupRectangles),
		"MergeOverlappingRectangles": reflect.ValueOf(basic.MergeOverlappingRectangles),
		"MinAreaRect":                reflect.ValueOf(basic.MinAreaRect),

		// type definitions
		"FPoint":    reflect.ValueOf((*basic.FPoint)(nil)),
		"OcrResult": reflect.ValueOf((*basic.OcrResult)(nil)),
		"OcrText":   reflect.ValueOf((*basic.OcrText)(nil)),
		"Point":     reflect.ValueOf((*basic.Point)(nil)),
		"Rect":      reflect.ValueOf((*basic.Rect)(nil)),
		"Size":      reflect.ValueOf((*basic.Size)(nil)),
	}
}
