// Code generated by 'yaegi extract yanlingrpa.com/yanling/protocol/script'. DO NOT EDIT.

package symbols

import (
	"reflect"
	"yanlingrpa.com/yanling/protocol/appgui"
	"yanlingrpa.com/yanling/protocol/browser"
	"yanlingrpa.com/yanling/protocol/component"
	"yanlingrpa.com/yanling/protocol/osgui"
	"yanlingrpa.com/yanling/protocol/ossys"
	"yanlingrpa.com/yanling/protocol/script"
)

func init() {
	Symbols["yanlingrpa.com/yanling/protocol/script/script"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ParseModuleSpec":  reflect.ValueOf(script.ParseModuleSpec),
		"VariableBoolean":  reflect.ValueOf(script.VariableBoolean),
		"VariableFilePath": reflect.ValueOf(script.VariableFilePath),
		"VariableInteger":  reflect.ValueOf(script.VariableInteger),
		"VariableJson":     reflect.ValueOf(script.VariableJson),
		"VariableNumber":   reflect.ValueOf(script.VariableNumber),
		"VariableString":   reflect.ValueOf(script.VariableString),

		// type definitions
		"Event":             reflect.ValueOf((*script.Event)(nil)),
		"EventHandler":      reflect.ValueOf((*script.EventHandler)(nil)),
		"GuiApplication":    reflect.ValueOf((*script.GuiApplication)(nil)),
		"MobileApplication": reflect.ValueOf((*script.MobileApplication)(nil)),
		"ModuleInfo":        reflect.ValueOf((*script.ModuleInfo)(nil)),
		"ModuleName":        reflect.ValueOf((*script.ModuleName)(nil)),
		"ModuleRuntime":     reflect.ValueOf((*script.ModuleRuntime)(nil)),
		"ScriptVariable":    reflect.ValueOf((*script.ScriptVariable)(nil)),
		"Subscriber":        reflect.ValueOf((*script.Subscriber)(nil)),
		"UrlPermission":     reflect.ValueOf((*script.UrlPermission)(nil)),
		"VariableDataType":  reflect.ValueOf((*script.VariableDataType)(nil)),
		"WebApplication":    reflect.ValueOf((*script.WebApplication)(nil)),
		"YScript":           reflect.ValueOf((*script.YScript)(nil)),

		// interface wrapper definitions
		"_ModuleRuntime": reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_script_ModuleRuntime)(nil)),
		"_Subscriber":    reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_script_Subscriber)(nil)),
	}
}

// _yanlingrpa_com_yanling_protocol_script_ModuleRuntime is an interface wrapper for ModuleRuntime type
type _yanlingrpa_com_yanling_protocol_script_ModuleRuntime struct {
	IValue            interface{}
	WBooleanVariable  func(name string) (bool, bool)
	WBrokerInfo       func() ossys.BrokerInfo
	WBrowserWindow    func(id string) (browser.BrowserWindow, bool)
	WCurrentSpecifier func() string
	WFilePathVariable func(name string) (string, bool)
	WFileSystem       func() ossys.LocalFilesystem
	WFloatVariable    func(name string) (float64, bool)
	WGetCacheData     func(key string) (string, bool)
	WHostSpecifier    func() string
	WHttpClient       func() ossys.HttpClient
	WIntegerVariable  func(name string) (int, bool)
	WInvokeWorker     func(specifier string, method string, dto any) (string, error)
	WJsonVariable     func(name string) (any, bool)
	WLogger           func() ossys.ScriptLogger
	WMobileWindow     func(id string) (appgui.AppGuiWindow, bool)
	WOcrWorker        func() component.OcrWorker
	WOsGuiWindow      func(id string) (osgui.OSGuiWindow, bool)
	WPublish          func(topic string, data any) error
	WSetCacheData     func(key string, value string)
	WStorage          func() ossys.LocalStorage
	WStringVariable   func(name string) (string, bool)
	WSubscribe        func(specifier string, topic string, handler script.EventHandler) (script.Subscriber, error)
	WUnsubscribe      func(subscriber script.Subscriber) error
	WVisionWorker     func() component.VisionWorker
}

func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) BooleanVariable(name string) (bool, bool) {
	return W.WBooleanVariable(name)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) BrokerInfo() ossys.BrokerInfo {
	return W.WBrokerInfo()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) BrowserWindow(id string) (browser.BrowserWindow, bool) {
	return W.WBrowserWindow(id)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) CurrentSpecifier() string {
	return W.WCurrentSpecifier()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) FilePathVariable(name string) (string, bool) {
	return W.WFilePathVariable(name)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) FileSystem() ossys.LocalFilesystem {
	return W.WFileSystem()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) FloatVariable(name string) (float64, bool) {
	return W.WFloatVariable(name)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) GetCacheData(key string) (string, bool) {
	return W.WGetCacheData(key)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) HostSpecifier() string {
	return W.WHostSpecifier()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) HttpClient() ossys.HttpClient {
	return W.WHttpClient()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) IntegerVariable(name string) (int, bool) {
	return W.WIntegerVariable(name)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) InvokeWorker(specifier string, method string, dto any) (string, error) {
	return W.WInvokeWorker(specifier, method, dto)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) JsonVariable(name string) (any, bool) {
	return W.WJsonVariable(name)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) Logger() ossys.ScriptLogger {
	return W.WLogger()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) MobileWindow(id string) (appgui.AppGuiWindow, bool) {
	return W.WMobileWindow(id)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) OcrWorker() component.OcrWorker {
	return W.WOcrWorker()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) OsGuiWindow(id string) (osgui.OSGuiWindow, bool) {
	return W.WOsGuiWindow(id)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) Publish(topic string, data any) error {
	return W.WPublish(topic, data)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) SetCacheData(key string, value string) {
	W.WSetCacheData(key, value)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) Storage() ossys.LocalStorage {
	return W.WStorage()
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) StringVariable(name string) (string, bool) {
	return W.WStringVariable(name)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) Subscribe(specifier string, topic string, handler script.EventHandler) (script.Subscriber, error) {
	return W.WSubscribe(specifier, topic, handler)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) Unsubscribe(subscriber script.Subscriber) error {
	return W.WUnsubscribe(subscriber)
}
func (W _yanlingrpa_com_yanling_protocol_script_ModuleRuntime) VisionWorker() component.VisionWorker {
	return W.WVisionWorker()
}

// _yanlingrpa_com_yanling_protocol_script_Subscriber is an interface wrapper for Subscriber type
type _yanlingrpa_com_yanling_protocol_script_Subscriber struct {
	IValue        interface{}
	WGetSpecifier func() string
	WGetTopic     func() string
	WIsActive     func() bool
}

func (W _yanlingrpa_com_yanling_protocol_script_Subscriber) GetSpecifier() string {
	return W.WGetSpecifier()
}
func (W _yanlingrpa_com_yanling_protocol_script_Subscriber) GetTopic() string {
	return W.WGetTopic()
}
func (W _yanlingrpa_com_yanling_protocol_script_Subscriber) IsActive() bool {
	return W.WIsActive()
}
