// Code generated by 'yaegi extract yanlingrpa.com/yanling/protocol/extension'. DO NOT EDIT.

package symbols

import (
	"reflect"
	"yanlingrpa.com/yanling/protocol/basic"
	"yanlingrpa.com/yanling/protocol/extension"
)

func init() {
	Symbols["yanlingrpa.com/yanling/protocol/extension/extension"] = map[string]reflect.Value{
		// type definitions
		"VisionExtension": reflect.ValueOf((*extension.VisionExtension)(nil)),

		// interface wrapper definitions
		"_VisionExtension": reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_extension_VisionExtension)(nil)),
	}
}

// _yanlingrpa_com_yanling_protocol_extension_VisionExtension is an interface wrapper for VisionExtension type
type _yanlingrpa_com_yanling_protocol_extension_VisionExtension struct {
	IValue  interface{}
	WDetect func(image []byte, instruction string, schema string) (string, error)
	WLocate func(image []byte, texts ...string) ([]basic.Rect, error)
	WOcr    func(image []byte) (*basic.OcrResult, error)
	WRead   func(image []byte, instruction string, schema string) (string, error)
}

func (W _yanlingrpa_com_yanling_protocol_extension_VisionExtension) Detect(image []byte, instruction string, schema string) (string, error) {
	return W.WDetect(image, instruction, schema)
}
func (W _yanlingrpa_com_yanling_protocol_extension_VisionExtension) Locate(image []byte, texts ...string) ([]basic.Rect, error) {
	return W.WLocate(image, texts...)
}
func (W _yanlingrpa_com_yanling_protocol_extension_VisionExtension) Ocr(image []byte) (*basic.OcrResult, error) {
	return W.WOcr(image)
}
func (W _yanlingrpa_com_yanling_protocol_extension_VisionExtension) Read(image []byte, instruction string, schema string) (string, error) {
	return W.WRead(image, instruction, schema)
}
