// Code generated by 'yaegi extract yanlingrpa.com/yanling/protocol/ossys'. DO NOT EDIT.

package symbols

import (
	"reflect"
	"time"
	"yanlingrpa.com/yanling/protocol/basic"
	"yanlingrpa.com/yanling/protocol/ossys"
)

func init() {
	Symbols["yanlingrpa.com/yanling/protocol/ossys/ossys"] = map[string]reflect.Value{
		// type definitions
		"BrokerInfo":         reflect.ValueOf((*ossys.BrokerInfo)(nil)),
		"HttpClient":         reflect.ValueOf((*ossys.HttpClient)(nil)),
		"HttpRequest":        reflect.ValueOf((*ossys.HttpRequest)(nil)),
		"HttpRequestOptions": reflect.ValueOf((*ossys.HttpRequestOptions)(nil)),
		"HttpResponse":       reflect.ValueOf((*ossys.HttpResponse)(nil)),
		"LocalFilesystem":    reflect.ValueOf((*ossys.LocalFilesystem)(nil)),
		"LocalStorage":       reflect.ValueOf((*ossys.LocalStorage)(nil)),
		"MonitorInfo":        reflect.ValueOf((*ossys.MonitorInfo)(nil)),
		"ScriptLogger":       reflect.ValueOf((*ossys.ScriptLogger)(nil)),

		// interface wrapper definitions
		"_BrokerInfo":      reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_ossys_BrokerInfo)(nil)),
		"_HttpClient":      reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_ossys_HttpClient)(nil)),
		"_LocalFilesystem": reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem)(nil)),
		"_LocalStorage":    reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_ossys_LocalStorage)(nil)),
		"_MonitorInfo":     reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_ossys_MonitorInfo)(nil)),
		"_ScriptLogger":    reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_ossys_ScriptLogger)(nil)),
	}
}

// _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo is an interface wrapper for BrokerInfo type
type _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo struct {
	IValue             interface{}
	WDeviceId          func() string
	WDeviceName        func() string
	WGetComputerName   func() string
	WGetGpuMemoryMB    func() int
	WGetMonitors       func() []ossys.MonitorInfo
	WGetPrimaryMonitor func() ossys.MonitorInfo
	WGetUserName       func() string
	WHasNvidiaGPU      func() bool
	WNumLogicCPU       func() int
	WOS                func() string
	WOSVersion         func() string
}

func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) DeviceId() string {
	return W.WDeviceId()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) DeviceName() string {
	return W.WDeviceName()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) GetComputerName() string {
	return W.WGetComputerName()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) GetGpuMemoryMB() int {
	return W.WGetGpuMemoryMB()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) GetMonitors() []ossys.MonitorInfo {
	return W.WGetMonitors()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) GetPrimaryMonitor() ossys.MonitorInfo {
	return W.WGetPrimaryMonitor()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) GetUserName() string {
	return W.WGetUserName()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) HasNvidiaGPU() bool {
	return W.WHasNvidiaGPU()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) NumLogicCPU() int {
	return W.WNumLogicCPU()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) OS() string {
	return W.WOS()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_BrokerInfo) OSVersion() string {
	return W.WOSVersion()
}

// _yanlingrpa_com_yanling_protocol_ossys_HttpClient is an interface wrapper for HttpClient type
type _yanlingrpa_com_yanling_protocol_ossys_HttpClient struct {
	IValue              interface{}
	WDeleteDomainCookie func(domain string, cookieNames ...string) error
	WDeleteDomainHeader func(domain string, headerNames ...string) error
	WDownloadFile       func(url string, headers map[string]string) (string, error)
	WDownloadFileTo     func(url string, savePath string, headers map[string]string, options ossys.HttpRequestOptions) (string, error)
	WGet                func(url string, headers map[string]string) ([]byte, error)
	WGetDomainCookies   func(domain string) (map[string]string, error)
	WGetDomainHeaders   func(domain string) (map[string]string, error)
	WPost               func(url string, body []byte, headers map[string]string) ([]byte, error)
	WPostForm           func(url string, params map[string]any, headers map[string]string) ([]byte, error)
	WPostJson           func(url string, params map[string]any, headers map[string]string) ([]byte, error)
	WRequest            func(req ossys.HttpRequest) (ossys.HttpResponse, error)
	WSetDomainCookies   func(domain string, cookies map[string]string) error
	WSetDomainHeaders   func(domain string, headers map[string]string) error
	WUploadData         func(url string, fileName string, fileData []byte, params map[string]any, headers map[string]string) ([]byte, error)
	WUploadFile         func(url string, filePath string, params map[string]any, headers map[string]string) ([]byte, error)
}

func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) DeleteDomainCookie(domain string, cookieNames ...string) error {
	return W.WDeleteDomainCookie(domain, cookieNames...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) DeleteDomainHeader(domain string, headerNames ...string) error {
	return W.WDeleteDomainHeader(domain, headerNames...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) DownloadFile(url string, headers map[string]string) (string, error) {
	return W.WDownloadFile(url, headers)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) DownloadFileTo(url string, savePath string, headers map[string]string, options ossys.HttpRequestOptions) (string, error) {
	return W.WDownloadFileTo(url, savePath, headers, options)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) Get(url string, headers map[string]string) ([]byte, error) {
	return W.WGet(url, headers)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) GetDomainCookies(domain string) (map[string]string, error) {
	return W.WGetDomainCookies(domain)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) GetDomainHeaders(domain string) (map[string]string, error) {
	return W.WGetDomainHeaders(domain)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) Post(url string, body []byte, headers map[string]string) ([]byte, error) {
	return W.WPost(url, body, headers)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) PostForm(url string, params map[string]any, headers map[string]string) ([]byte, error) {
	return W.WPostForm(url, params, headers)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) PostJson(url string, params map[string]any, headers map[string]string) ([]byte, error) {
	return W.WPostJson(url, params, headers)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) Request(req ossys.HttpRequest) (ossys.HttpResponse, error) {
	return W.WRequest(req)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) SetDomainCookies(domain string, cookies map[string]string) error {
	return W.WSetDomainCookies(domain, cookies)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) SetDomainHeaders(domain string, headers map[string]string) error {
	return W.WSetDomainHeaders(domain, headers)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) UploadData(url string, fileName string, fileData []byte, params map[string]any, headers map[string]string) ([]byte, error) {
	return W.WUploadData(url, fileName, fileData, params, headers)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_HttpClient) UploadFile(url string, filePath string, params map[string]any, headers map[string]string) ([]byte, error) {
	return W.WUploadFile(url, filePath, params, headers)
}

// _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem is an interface wrapper for LocalFilesystem type
type _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem struct {
	IValue         interface{}
	WCopyFile      func(src string, dst string) error
	WCreateTmpFile func(expiredAt time.Time) (string, error)
	WDataRoot      func() string
	WIsDir         func(path string) (bool, error)
	WIsFile        func(path string) (bool, error)
	WJoinPath      func(path ...string) string
	WListDir       func(path string) ([]string, error)
	WMkdir         func(path string) error
	WMkdirAll      func(path string) error
	WPathExists    func(path string) (bool, error)
	WReadFile      func(filePath string) ([]byte, error)
	WRemove        func(path string) error
	WRemoveAll     func(path string) error
	WRename        func(src string, dst string) error
	WScriptRoot    func() string
	WStatPath      func(path string) (exists bool, isDir bool, size int64, modifiedAt time.Time, err error)
	WWriteFile     func(filePath string, data []byte) error
}

func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) CopyFile(src string, dst string) error {
	return W.WCopyFile(src, dst)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) CreateTmpFile(expiredAt time.Time) (string, error) {
	return W.WCreateTmpFile(expiredAt)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) DataRoot() string {
	return W.WDataRoot()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) IsDir(path string) (bool, error) {
	return W.WIsDir(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) IsFile(path string) (bool, error) {
	return W.WIsFile(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) JoinPath(path ...string) string {
	return W.WJoinPath(path...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) ListDir(path string) ([]string, error) {
	return W.WListDir(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) Mkdir(path string) error {
	return W.WMkdir(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) MkdirAll(path string) error {
	return W.WMkdirAll(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) PathExists(path string) (bool, error) {
	return W.WPathExists(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) ReadFile(filePath string) ([]byte, error) {
	return W.WReadFile(filePath)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) Remove(path string) error {
	return W.WRemove(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) RemoveAll(path string) error {
	return W.WRemoveAll(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) Rename(src string, dst string) error {
	return W.WRename(src, dst)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) ScriptRoot() string {
	return W.WScriptRoot()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) StatPath(path string) (exists bool, isDir bool, size int64, modifiedAt time.Time, err error) {
	return W.WStatPath(path)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalFilesystem) WriteFile(filePath string, data []byte) error {
	return W.WWriteFile(filePath, data)
}

// _yanlingrpa_com_yanling_protocol_ossys_LocalStorage is an interface wrapper for LocalStorage type
type _yanlingrpa_com_yanling_protocol_ossys_LocalStorage struct {
	IValue  interface{}
	WDel    func(keys ...string) int
	WGet    func(key string) string
	WKeys   func() []string
	WMGet   func(keys ...string) map[string]string
	WMSet   func(data map[string]string)
	WMSetEx func(data map[string]string, expiredAt int64)
	WSet    func(key string, value string)
	WSetEx  func(key string, value string, expiredAt int64)
}

func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) Del(keys ...string) int {
	return W.WDel(keys...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) Get(key string) string {
	return W.WGet(key)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) Keys() []string {
	return W.WKeys()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) MGet(keys ...string) map[string]string {
	return W.WMGet(keys...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) MSet(data map[string]string) {
	W.WMSet(data)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) MSetEx(data map[string]string, expiredAt int64) {
	W.WMSetEx(data, expiredAt)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) Set(key string, value string) {
	W.WSet(key, value)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_LocalStorage) SetEx(key string, value string, expiredAt int64) {
	W.WSetEx(key, value, expiredAt)
}

// _yanlingrpa_com_yanling_protocol_ossys_MonitorInfo is an interface wrapper for MonitorInfo type
type _yanlingrpa_com_yanling_protocol_ossys_MonitorInfo struct {
	IValue       interface{}
	WGetBounds   func() basic.Rect
	WGetDPI      func() uint32
	WGetWorkArea func() basic.Rect
	WIsPrimary   func() bool
}

func (W _yanlingrpa_com_yanling_protocol_ossys_MonitorInfo) GetBounds() basic.Rect {
	return W.WGetBounds()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_MonitorInfo) GetDPI() uint32 {
	return W.WGetDPI()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_MonitorInfo) GetWorkArea() basic.Rect {
	return W.WGetWorkArea()
}
func (W _yanlingrpa_com_yanling_protocol_ossys_MonitorInfo) IsPrimary() bool {
	return W.WIsPrimary()
}

// _yanlingrpa_com_yanling_protocol_ossys_ScriptLogger is an interface wrapper for ScriptLogger type
type _yanlingrpa_com_yanling_protocol_ossys_ScriptLogger struct {
	IValue interface{}
	WDebug func(format string, args ...any)
	WError func(format string, args ...any)
	WInfo  func(format string, args ...any)
	WWarn  func(format string, args ...any)
}

func (W _yanlingrpa_com_yanling_protocol_ossys_ScriptLogger) Debug(format string, args ...any) {
	W.WDebug(format, args...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_ScriptLogger) Error(format string, args ...any) {
	W.WError(format, args...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_ScriptLogger) Info(format string, args ...any) {
	W.WInfo(format, args...)
}
func (W _yanlingrpa_com_yanling_protocol_ossys_ScriptLogger) Warn(format string, args ...any) {
	W.WWarn(format, args...)
}
