// Code generated by 'yaegi extract yanlingrpa.com/yanling/protocol/osgui'. DO NOT EDIT.

package symbols

import (
	"reflect"
	"time"
	"yanlingrpa.com/yanling/protocol/basic"
	"yanlingrpa.com/yanling/protocol/osgui"
	"yanlingrpa.com/yanling/protocol/ossys"
)

func init() {
	Symbols["yanlingrpa.com/yanling/protocol/osgui/osgui"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Alt":             reflect.ValueOf(osgui.Alt),
		"AudioForward":    reflect.ValueOf(osgui.AudioForward),
		"AudioMute":       reflect.ValueOf(osgui.AudioMute),
		"AudioNext":       reflect.ValueOf(osgui.AudioNext),
		"AudioPause":      reflect.ValueOf(osgui.AudioPause),
		"AudioPlay":       reflect.ValueOf(osgui.AudioPlay),
		"AudioPrev":       reflect.ValueOf(osgui.AudioPrev),
		"AudioRandom":     reflect.ValueOf(osgui.AudioRandom),
		"AudioRepeat":     reflect.ValueOf(osgui.AudioRepeat),
		"AudioRewind":     reflect.ValueOf(osgui.AudioRewind),
		"AudioStop":       reflect.ValueOf(osgui.AudioStop),
		"AudioVolDown":    reflect.ValueOf(osgui.AudioVolDown),
		"AudioVolUp":      reflect.ValueOf(osgui.AudioVolUp),
		"Backspace":       reflect.ValueOf(osgui.Backspace),
		"CapA":            reflect.ValueOf(osgui.CapA),
		"CapB":            reflect.ValueOf(osgui.CapB),
		"CapC":            reflect.ValueOf(osgui.CapC),
		"CapD":            reflect.ValueOf(osgui.CapD),
		"CapE":            reflect.ValueOf(osgui.CapE),
		"CapF":            reflect.ValueOf(osgui.CapF),
		"CapG":            reflect.ValueOf(osgui.CapG),
		"CapH":            reflect.ValueOf(osgui.CapH),
		"CapI":            reflect.ValueOf(osgui.CapI),
		"CapJ":            reflect.ValueOf(osgui.CapJ),
		"CapK":            reflect.ValueOf(osgui.CapK),
		"CapL":            reflect.ValueOf(osgui.CapL),
		"CapM":            reflect.ValueOf(osgui.CapM),
		"CapN":            reflect.ValueOf(osgui.CapN),
		"CapO":            reflect.ValueOf(osgui.CapO),
		"CapP":            reflect.ValueOf(osgui.CapP),
		"CapQ":            reflect.ValueOf(osgui.CapQ),
		"CapR":            reflect.ValueOf(osgui.CapR),
		"CapS":            reflect.ValueOf(osgui.CapS),
		"CapT":            reflect.ValueOf(osgui.CapT),
		"CapU":            reflect.ValueOf(osgui.CapU),
		"CapV":            reflect.ValueOf(osgui.CapV),
		"CapW":            reflect.ValueOf(osgui.CapW),
		"CapX":            reflect.ValueOf(osgui.CapX),
		"CapY":            reflect.ValueOf(osgui.CapY),
		"CapZ":            reflect.ValueOf(osgui.CapZ),
		"Capslock":        reflect.ValueOf(osgui.Capslock),
		"Cmd":             reflect.ValueOf(osgui.Cmd),
		"Control":         reflect.ValueOf(osgui.Control),
		"Ctrl":            reflect.ValueOf(osgui.Ctrl),
		"Delete":          reflect.ValueOf(osgui.Delete),
		"Down":            reflect.ValueOf(osgui.Down),
		"End":             reflect.ValueOf(osgui.End),
		"Enter":           reflect.ValueOf(osgui.Enter),
		"Esc":             reflect.ValueOf(osgui.Esc),
		"Escape":          reflect.ValueOf(osgui.Escape),
		"F1":              reflect.ValueOf(osgui.F1),
		"F10":             reflect.ValueOf(osgui.F10),
		"F11":             reflect.ValueOf(osgui.F11),
		"F12":             reflect.ValueOf(osgui.F12),
		"F13":             reflect.ValueOf(osgui.F13),
		"F14":             reflect.ValueOf(osgui.F14),
		"F15":             reflect.ValueOf(osgui.F15),
		"F16":             reflect.ValueOf(osgui.F16),
		"F17":             reflect.ValueOf(osgui.F17),
		"F18":             reflect.ValueOf(osgui.F18),
		"F19":             reflect.ValueOf(osgui.F19),
		"F2":              reflect.ValueOf(osgui.F2),
		"F20":             reflect.ValueOf(osgui.F20),
		"F21":             reflect.ValueOf(osgui.F21),
		"F22":             reflect.ValueOf(osgui.F22),
		"F23":             reflect.ValueOf(osgui.F23),
		"F24":             reflect.ValueOf(osgui.F24),
		"F3":              reflect.ValueOf(osgui.F3),
		"F4":              reflect.ValueOf(osgui.F4),
		"F5":              reflect.ValueOf(osgui.F5),
		"F6":              reflect.ValueOf(osgui.F6),
		"F7":              reflect.ValueOf(osgui.F7),
		"F8":              reflect.ValueOf(osgui.F8),
		"F9":              reflect.ValueOf(osgui.F9),
		"Home":            reflect.ValueOf(osgui.Home),
		"Insert":          reflect.ValueOf(osgui.Insert),
		"Key0":            reflect.ValueOf(osgui.Key0),
		"Key1":            reflect.ValueOf(osgui.Key1),
		"Key2":            reflect.ValueOf(osgui.Key2),
		"Key3":            reflect.ValueOf(osgui.Key3),
		"Key4":            reflect.ValueOf(osgui.Key4),
		"Key5":            reflect.ValueOf(osgui.Key5),
		"Key6":            reflect.ValueOf(osgui.Key6),
		"Key7":            reflect.ValueOf(osgui.Key7),
		"Key8":            reflect.ValueOf(osgui.Key8),
		"Key9":            reflect.ValueOf(osgui.Key9),
		"KeyA":            reflect.ValueOf(osgui.KeyA),
		"KeyB":            reflect.ValueOf(osgui.KeyB),
		"KeyC":            reflect.ValueOf(osgui.KeyC),
		"KeyD":            reflect.ValueOf(osgui.KeyD),
		"KeyE":            reflect.ValueOf(osgui.KeyE),
		"KeyF":            reflect.ValueOf(osgui.KeyF),
		"KeyG":            reflect.ValueOf(osgui.KeyG),
		"KeyH":            reflect.ValueOf(osgui.KeyH),
		"KeyI":            reflect.ValueOf(osgui.KeyI),
		"KeyJ":            reflect.ValueOf(osgui.KeyJ),
		"KeyK":            reflect.ValueOf(osgui.KeyK),
		"KeyL":            reflect.ValueOf(osgui.KeyL),
		"KeyM":            reflect.ValueOf(osgui.KeyM),
		"KeyN":            reflect.ValueOf(osgui.KeyN),
		"KeyO":            reflect.ValueOf(osgui.KeyO),
		"KeyP":            reflect.ValueOf(osgui.KeyP),
		"KeyQ":            reflect.ValueOf(osgui.KeyQ),
		"KeyR":            reflect.ValueOf(osgui.KeyR),
		"KeyS":            reflect.ValueOf(osgui.KeyS),
		"KeyT":            reflect.ValueOf(osgui.KeyT),
		"KeyU":            reflect.ValueOf(osgui.KeyU),
		"KeyV":            reflect.ValueOf(osgui.KeyV),
		"KeyW":            reflect.ValueOf(osgui.KeyW),
		"KeyX":            reflect.ValueOf(osgui.KeyX),
		"KeyY":            reflect.ValueOf(osgui.KeyY),
		"KeyZ":            reflect.ValueOf(osgui.KeyZ),
		"Lalt":            reflect.ValueOf(osgui.Lalt),
		"Lcmd":            reflect.ValueOf(osgui.Lcmd),
		"Lctrl":           reflect.ValueOf(osgui.Lctrl),
		"Left":            reflect.ValueOf(osgui.Left),
		"LightsKbdDown":   reflect.ValueOf(osgui.LightsKbdDown),
		"LightsKbdToggle": reflect.ValueOf(osgui.LightsKbdToggle),
		"LightsKbdUp":     reflect.ValueOf(osgui.LightsKbdUp),
		"LightsMonDown":   reflect.ValueOf(osgui.LightsMonDown),
		"LightsMonUp":     reflect.ValueOf(osgui.LightsMonUp),
		"Lshift":          reflect.ValueOf(osgui.Lshift),
		"Menu":            reflect.ValueOf(osgui.Menu),
		"Num0":            reflect.ValueOf(osgui.Num0),
		"Num1":            reflect.ValueOf(osgui.Num1),
		"Num2":            reflect.ValueOf(osgui.Num2),
		"Num3":            reflect.ValueOf(osgui.Num3),
		"Num4":            reflect.ValueOf(osgui.Num4),
		"Num5":            reflect.ValueOf(osgui.Num5),
		"Num6":            reflect.ValueOf(osgui.Num6),
		"Num7":            reflect.ValueOf(osgui.Num7),
		"Num8":            reflect.ValueOf(osgui.Num8),
		"NumClear":        reflect.ValueOf(osgui.NumClear),
		"NumDecimal":      reflect.ValueOf(osgui.NumDecimal),
		"NumDiv":          reflect.ValueOf(osgui.NumDiv),
		"NumEnter":        reflect.ValueOf(osgui.NumEnter),
		"NumEqual":        reflect.ValueOf(osgui.NumEqual),
		"NumLock":         reflect.ValueOf(osgui.NumLock),
		"NumMinus":        reflect.ValueOf(osgui.NumMinus),
		"NumMul":          reflect.ValueOf(osgui.NumMul),
		"NumPlus":         reflect.ValueOf(osgui.NumPlus),
		"Pagedown":        reflect.ValueOf(osgui.Pagedown),
		"Pageup":          reflect.ValueOf(osgui.Pageup),
		"Print":           reflect.ValueOf(osgui.Print),
		"Printscreen":     reflect.ValueOf(osgui.Printscreen),
		"Ralt":            reflect.ValueOf(osgui.Ralt),
		"Rcmd":            reflect.ValueOf(osgui.Rcmd),
		"Rctrl":           reflect.ValueOf(osgui.Rctrl),
		"Right":           reflect.ValueOf(osgui.Right),
		"Rshift":          reflect.ValueOf(osgui.Rshift),
		"Shift":           reflect.ValueOf(osgui.Shift),
		"Space":           reflect.ValueOf(osgui.Space),
		"Tab":             reflect.ValueOf(osgui.Tab),
		"Up":              reflect.ValueOf(osgui.Up),

		// type definitions
		"GuiWindow": reflect.ValueOf((*osgui.GuiWindow)(nil)),
		"Keyboard":  reflect.ValueOf((*osgui.Keyboard)(nil)),
		"Locator":   reflect.ValueOf((*osgui.Locator)(nil)),

		// interface wrapper definitions
		"_GuiWindow": reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_osgui_GuiWindow)(nil)),
		"_Locator":   reflect.ValueOf((*_yanlingrpa_com_yanling_protocol_osgui_Locator)(nil)),
	}
}

// _yanlingrpa_com_yanling_protocol_osgui_GuiWindow is an interface wrapper for GuiWindow type
type _yanlingrpa_com_yanling_protocol_osgui_GuiWindow struct {
	IValue              interface{}
	WActivate           func() (bool, error)
	WBodyLocator        func() (osgui.Locator, error)
	WClose              func() error
	WDeActivate         func() (bool, error)
	WGetClientRect      func() basic.Rect
	WGetHwnd            func() uintptr
	WGetID              func() string
	WGetInitiatorPath   func() string
	WGetMonitor         func() ossys.MonitorInfo
	WGetWindowCaretPos  func() *basic.Point
	WGetWindowCursorPos func() *basic.Point
	WGetWindowRect      func() basic.Rect
	WGetWindowSchema    func() string
	WGetWindowTitle     func() string
	WMoveTo             func(global_x int, global_y int) (bool, error)
	WPressKeys          func(keys ...osgui.Keyboard) error
	WReadClipboard      func() (string, error)
	WRectLocator        func(rect basic.Rect) (osgui.Locator, error)
	WResizeTo           func(width int, height int) (bool, error)
	WSnapshot           func(gray bool) ([]byte, error)
	WToMap              func() map[string]any
	WTransFromScreen    func(screen_pos *basic.Point) *basic.Point
	WTransToScreen      func(window_pos *basic.Point) *basic.Point
	WWriteClipboard     func(text string) error
}

func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) Activate() (bool, error) {
	return W.WActivate()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) BodyLocator() (osgui.Locator, error) {
	return W.WBodyLocator()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) Close() error {
	return W.WClose()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) DeActivate() (bool, error) {
	return W.WDeActivate()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetClientRect() basic.Rect {
	return W.WGetClientRect()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetHwnd() uintptr {
	return W.WGetHwnd()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetID() string {
	return W.WGetID()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetInitiatorPath() string {
	return W.WGetInitiatorPath()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetMonitor() ossys.MonitorInfo {
	return W.WGetMonitor()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetWindowCaretPos() *basic.Point {
	return W.WGetWindowCaretPos()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetWindowCursorPos() *basic.Point {
	return W.WGetWindowCursorPos()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetWindowRect() basic.Rect {
	return W.WGetWindowRect()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetWindowSchema() string {
	return W.WGetWindowSchema()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) GetWindowTitle() string {
	return W.WGetWindowTitle()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) MoveTo(global_x int, global_y int) (bool, error) {
	return W.WMoveTo(global_x, global_y)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) PressKeys(keys ...osgui.Keyboard) error {
	return W.WPressKeys(keys...)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) ReadClipboard() (string, error) {
	return W.WReadClipboard()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) RectLocator(rect basic.Rect) (osgui.Locator, error) {
	return W.WRectLocator(rect)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) ResizeTo(width int, height int) (bool, error) {
	return W.WResizeTo(width, height)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) Snapshot(gray bool) ([]byte, error) {
	return W.WSnapshot(gray)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) ToMap() map[string]any {
	return W.WToMap()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) TransFromScreen(screen_pos *basic.Point) *basic.Point {
	return W.WTransFromScreen(screen_pos)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) TransToScreen(window_pos *basic.Point) *basic.Point {
	return W.WTransToScreen(window_pos)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_GuiWindow) WriteClipboard(text string) error {
	return W.WWriteClipboard(text)
}

// _yanlingrpa_com_yanling_protocol_osgui_Locator is an interface wrapper for Locator type
type _yanlingrpa_com_yanling_protocol_osgui_Locator struct {
	IValue               interface{}
	WCanScrollHorizontal func() bool
	WCanScrollVertical   func() bool
	WCardLocator         func(min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error)
	WClearText           func() error
	WClick               func(locator_point *basic.Point) error
	WDoubleClick         func(locator_point *basic.Point) error
	WDragTo              func(from_locator_point *basic.Point, to_locator_point *basic.Point) error
	WFocus               func() error
	WGetBodyRect         func() basic.Rect
	WGetLocatorCaretPos  func() *basic.Point
	WGetLocatorCursorPos func() *basic.Point
	WGetScreenRect       func() basic.Rect
	WGetSize             func() basic.Size
	WGetWindowRect       func() basic.Rect
	WImageLocator        func(image string, sim float32) ([]osgui.Locator, error)
	WIsEditing           func() bool
	WMouseDown           func(right bool) error
	WMouseMove           func(locator_point *basic.Point) error
	WMouseUp             func(right bool) error
	WOcrRead             func(confidence float64) (*basic.OcrResult, error)
	WPressKeys           func(keys ...osgui.Keyboard) error
	WReadText            func() (string, error)
	WRightClick          func(locator_point *basic.Point) error
	WScrollHorizontal    func(forward bool, distance int) error
	WScrollVertical      func(forward bool, distance int) error
	WSnapshot            func(gray bool) ([]byte, error)
	WSubLocator          func(locator_point basic.Point, size basic.Size) osgui.Locator
	WTextLocator         func(texts ...string) ([]osgui.Locator, error)
	WToMap               func() map[string]any
	WTransFromBody       func(body_pos *basic.Point) *basic.Point
	WTransFromScreen     func(screen_pos *basic.Point) *basic.Point
	WTransFromWindow     func(window_pos *basic.Point) *basic.Point
	WTransToBody         func(locator_point *basic.Point) *basic.Point
	WTransToScreen       func(locator_point *basic.Point) *basic.Point
	WTransToWindow       func(locator_point *basic.Point) *basic.Point
	WVisionLocator       func(description string, min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error)
	WWaitForCard         func(timeout time.Duration, min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error)
	WWaitForEditing      func(timeout time.Duration) (osgui.Locator, error)
	WWaitForImage        func(timeout time.Duration, image string, sim float32) ([]osgui.Locator, error)
	WWaitForText         func(timeout time.Duration, texts ...string) ([]osgui.Locator, error)
	WWaitForVision       func(timeout time.Duration, description string, min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error)
	WWriteText           func(text string) error
}

func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) CanScrollHorizontal() bool {
	return W.WCanScrollHorizontal()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) CanScrollVertical() bool {
	return W.WCanScrollVertical()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) CardLocator(min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error) {
	return W.WCardLocator(min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) ClearText() error {
	return W.WClearText()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) Click(locator_point *basic.Point) error {
	return W.WClick(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) DoubleClick(locator_point *basic.Point) error {
	return W.WDoubleClick(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) DragTo(from_locator_point *basic.Point, to_locator_point *basic.Point) error {
	return W.WDragTo(from_locator_point, to_locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) Focus() error {
	return W.WFocus()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) GetBodyRect() basic.Rect {
	return W.WGetBodyRect()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) GetLocatorCaretPos() *basic.Point {
	return W.WGetLocatorCaretPos()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) GetLocatorCursorPos() *basic.Point {
	return W.WGetLocatorCursorPos()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) GetScreenRect() basic.Rect {
	return W.WGetScreenRect()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) GetSize() basic.Size {
	return W.WGetSize()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) GetWindowRect() basic.Rect {
	return W.WGetWindowRect()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) ImageLocator(image string, sim float32) ([]osgui.Locator, error) {
	return W.WImageLocator(image, sim)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) IsEditing() bool {
	return W.WIsEditing()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) MouseDown(right bool) error {
	return W.WMouseDown(right)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) MouseMove(locator_point *basic.Point) error {
	return W.WMouseMove(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) MouseUp(right bool) error {
	return W.WMouseUp(right)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) OcrRead(confidence float64) (*basic.OcrResult, error) {
	return W.WOcrRead(confidence)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) PressKeys(keys ...osgui.Keyboard) error {
	return W.WPressKeys(keys...)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) ReadText() (string, error) {
	return W.WReadText()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) RightClick(locator_point *basic.Point) error {
	return W.WRightClick(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) ScrollHorizontal(forward bool, distance int) error {
	return W.WScrollHorizontal(forward, distance)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) ScrollVertical(forward bool, distance int) error {
	return W.WScrollVertical(forward, distance)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) Snapshot(gray bool) ([]byte, error) {
	return W.WSnapshot(gray)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) SubLocator(locator_point basic.Point, size basic.Size) osgui.Locator {
	return W.WSubLocator(locator_point, size)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) TextLocator(texts ...string) ([]osgui.Locator, error) {
	return W.WTextLocator(texts...)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) ToMap() map[string]any {
	return W.WToMap()
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) TransFromBody(body_pos *basic.Point) *basic.Point {
	return W.WTransFromBody(body_pos)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) TransFromScreen(screen_pos *basic.Point) *basic.Point {
	return W.WTransFromScreen(screen_pos)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) TransFromWindow(window_pos *basic.Point) *basic.Point {
	return W.WTransFromWindow(window_pos)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) TransToBody(locator_point *basic.Point) *basic.Point {
	return W.WTransToBody(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) TransToScreen(locator_point *basic.Point) *basic.Point {
	return W.WTransToScreen(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) TransToWindow(locator_point *basic.Point) *basic.Point {
	return W.WTransToWindow(locator_point)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) VisionLocator(description string, min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error) {
	return W.WVisionLocator(description, min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) WaitForCard(timeout time.Duration, min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error) {
	return W.WWaitForCard(timeout, min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) WaitForEditing(timeout time.Duration) (osgui.Locator, error) {
	return W.WWaitForEditing(timeout)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) WaitForImage(timeout time.Duration, image string, sim float32) ([]osgui.Locator, error) {
	return W.WWaitForImage(timeout, image, sim)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) WaitForText(timeout time.Duration, texts ...string) ([]osgui.Locator, error) {
	return W.WWaitForText(timeout, texts...)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) WaitForVision(timeout time.Duration, description string, min_size *basic.Size, max_size *basic.Size) ([]osgui.Locator, error) {
	return W.WWaitForVision(timeout, description, min_size, max_size)
}
func (W _yanlingrpa_com_yanling_protocol_osgui_Locator) WriteText(text string) error {
	return W.WWriteText(text)
}
