// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/yanling_script.proto

package proto

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VariableDataType defines data types for script variables.
type VariableDataType int32

const (
	VariableDataType_VARIABLE_DATA_TYPE_UNSPECIFIED VariableDataType = 0
	VariableDataType_VARIABLE_BOOLEAN               VariableDataType = 1
	VariableDataType_VARIABLE_STRING                VariableDataType = 2
	VariableDataType_VARIABLE_FILE_PATH             VariableDataType = 3
	VariableDataType_VARIABLE_INTEGER               VariableDataType = 4
	VariableDataType_VARIABLE_NUMBER                VariableDataType = 5
	VariableDataType_VARIABLE_JSON                  VariableDataType = 6
)

// Enum value maps for VariableDataType.
var (
	VariableDataType_name = map[int32]string{
		0: "VARIABLE_DATA_TYPE_UNSPECIFIED",
		1: "VARIABLE_BOOLEAN",
		2: "VARIABLE_STRING",
		3: "VARIABLE_FILE_PATH",
		4: "VARIABLE_INTEGER",
		5: "VARIABLE_NUMBER",
		6: "VARIABLE_JSON",
	}
	VariableDataType_value = map[string]int32{
		"VARIABLE_DATA_TYPE_UNSPECIFIED": 0,
		"VARIABLE_BOOLEAN":               1,
		"VARIABLE_STRING":                2,
		"VARIABLE_FILE_PATH":             3,
		"VARIABLE_INTEGER":               4,
		"VARIABLE_NUMBER":                5,
		"VARIABLE_JSON":                  6,
	}
)

func (x VariableDataType) Enum() *VariableDataType {
	p := new(VariableDataType)
	*p = x
	return p
}

func (x VariableDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VariableDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_yanling_script_proto_enumTypes[0].Descriptor()
}

func (VariableDataType) Type() protoreflect.EnumType {
	return &file_proto_yanling_script_proto_enumTypes[0]
}

func (x VariableDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VariableDataType.Descriptor instead.
func (VariableDataType) EnumDescriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{0}
}

// ModuleInfo defines script module metadata.
type ModuleInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specifier is the module identifier, including domain, owner, name, and version,
	// parsed from the go.mod file.
	Specifier string `protobuf:"bytes,1,opt,name=specifier,proto3" json:"specifier,omitempty"`
	// Package is the script package name. Only scripts under this package can be imported and called.
	Package string `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	// Description describes script functionality and usage.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Tags is a list of script topic tags, for example ["web automation", "data extraction"].
	Tags []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	// Website is the official website of the script.
	Website string `protobuf:"bytes,5,opt,name=website,proto3" json:"website,omitempty"`
	// UpdateTime is the last update time (last commit time), formatted as RFC3339.
	UpdateTime string `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	// Author is the script author.
	Author string `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"`
	// Email is the contact email address.
	Email string `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	// License is the license, based on the LICENSE file or declaration.
	License string `protobuf:"bytes,9,opt,name=license,proto3" json:"license,omitempty"`
	// Devices is the list of applicable devices, for example ["windows", "mac", "ubuntu"].
	Devices []string `protobuf:"bytes,10,rep,name=devices,proto3" json:"devices,omitempty"`
	// EngineVersion is the required engine version.
	EngineVersion string `protobuf:"bytes,11,opt,name=engine_version,json=engineVersion,proto3" json:"engine_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModuleInfo) Reset() {
	*x = ModuleInfo{}
	mi := &file_proto_yanling_script_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModuleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModuleInfo) ProtoMessage() {}

func (x *ModuleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModuleInfo.ProtoReflect.Descriptor instead.
func (*ModuleInfo) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{0}
}

func (x *ModuleInfo) GetSpecifier() string {
	if x != nil {
		return x.Specifier
	}
	return ""
}

func (x *ModuleInfo) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *ModuleInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ModuleInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ModuleInfo) GetWebsite() string {
	if x != nil {
		return x.Website
	}
	return ""
}

func (x *ModuleInfo) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

func (x *ModuleInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ModuleInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ModuleInfo) GetLicense() string {
	if x != nil {
		return x.License
	}
	return ""
}

func (x *ModuleInfo) GetDevices() []string {
	if x != nil {
		return x.Devices
	}
	return nil
}

func (x *ModuleInfo) GetEngineVersion() string {
	if x != nil {
		return x.EngineVersion
	}
	return ""
}

// GuiApplication defines GUI application configuration.
type GuiApplication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is the unique identifier of the GUI application.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name is the GUI application name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Launcher is the launcher command or executable path, for example C:\Program Files\App\app.exe or /usr/bin/app.
	Launcher string `protobuf:"bytes,3,opt,name=launcher,proto3" json:"launcher,omitempty"`
	// Args is the command-line arguments passed to the launcher, for example ["--headless", "--no-sandbox"].
	Args []string `protobuf:"bytes,4,rep,name=args,proto3" json:"args,omitempty"`
	// WorkDir is the working directory for the launched application.
	// If empty, defaults to the directory of the launcher executable.
	WorkDir string `protobuf:"bytes,5,opt,name=work_dir,json=workDir,proto3" json:"work_dir,omitempty"`
	// Env is a list of environment variables in the format KEY=VALUE, for example ["PATH=/usr/bin", "DEBUG=1"].
	Env []string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty"`
	// Process is the process name associated with the GUI window, used for window detection and management.
	Process string `protobuf:"bytes,7,opt,name=process,proto3" json:"process,omitempty"`
	// LaunchUri is the URI used to open the GUI window, for example weixin://launchapplet?appid=xxxx.
	// If provided, the application will be launched and this URI will be opened.
	LaunchUri string `protobuf:"bytes,8,opt,name=launch_uri,json=launchUri,proto3" json:"launch_uri,omitempty"`
	// Timeout is the timeout in milliseconds for launching the application.
	// If 0, no timeout limit is applied.
	Timeout int32 `protobuf:"varint,9,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// WaitTime is the wait time in milliseconds after launching the application before returning.
	// Useful for allowing the GUI to fully initialize.
	WaitTime int32 `protobuf:"varint,10,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`
	// WindowWidth is the preferred window width in pixels. If 0, uses default.
	WindowWidth int32 `protobuf:"varint,11,opt,name=window_width,json=windowWidth,proto3" json:"window_width,omitempty"`
	// WindowHeight is the preferred window height in pixels. If 0, uses default.
	WindowHeight  int32 `protobuf:"varint,12,opt,name=window_height,json=windowHeight,proto3" json:"window_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GuiApplication) Reset() {
	*x = GuiApplication{}
	mi := &file_proto_yanling_script_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GuiApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuiApplication) ProtoMessage() {}

func (x *GuiApplication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuiApplication.ProtoReflect.Descriptor instead.
func (*GuiApplication) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{1}
}

func (x *GuiApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GuiApplication) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GuiApplication) GetLauncher() string {
	if x != nil {
		return x.Launcher
	}
	return ""
}

func (x *GuiApplication) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *GuiApplication) GetWorkDir() string {
	if x != nil {
		return x.WorkDir
	}
	return ""
}

func (x *GuiApplication) GetEnv() []string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *GuiApplication) GetProcess() string {
	if x != nil {
		return x.Process
	}
	return ""
}

func (x *GuiApplication) GetLaunchUri() string {
	if x != nil {
		return x.LaunchUri
	}
	return ""
}

func (x *GuiApplication) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *GuiApplication) GetWaitTime() int32 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

func (x *GuiApplication) GetWindowWidth() int32 {
	if x != nil {
		return x.WindowWidth
	}
	return 0
}

func (x *GuiApplication) GetWindowHeight() int32 {
	if x != nil {
		return x.WindowHeight
	}
	return 0
}

// WebApplication defines browser application configuration.
type WebApplication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is the unique identifier of the browser application.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name is the browser application name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// BrowserType is the browser type to use, for example "chrome", "firefox", "edge", "safari".
	// If empty, defaults to system default browser.
	BrowserType string `protobuf:"bytes,3,opt,name=browser_type,json=browserType,proto3" json:"browser_type,omitempty"`
	// Url is the browser application URL to open, for example https://www.google.com.
	Url string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// Incognito indicates whether to open the browser in private/incognito mode.
	Incognito bool `protobuf:"varint,5,opt,name=incognito,proto3" json:"incognito,omitempty"`
	// Args is a list of additional browser command-line arguments, for example ["--proxy-server=localhost:8080", "--disable-plugins"].
	Args []string `protobuf:"bytes,6,rep,name=args,proto3" json:"args,omitempty"`
	// UserDataDir is the custom user data directory for the browser profile.
	// If empty, uses the default profile directory.
	UserDataDir string `protobuf:"bytes,7,opt,name=user_data_dir,json=userDataDir,proto3" json:"user_data_dir,omitempty"`
	// LoadTimeout is the timeout in milliseconds for page loading.
	// If 0, no timeout limit is applied.
	LoadTimeout int32 `protobuf:"varint,8,opt,name=load_timeout,json=loadTimeout,proto3" json:"load_timeout,omitempty"`
	// WaitTime is the wait time in milliseconds after opening the URL before returning.
	// Useful for allowing the page to fully load.
	WaitTime int32 `protobuf:"varint,9,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`
	// WindowWidth is the preferred window width in pixels. If 0, uses default.
	WindowWidth int32 `protobuf:"varint,10,opt,name=window_width,json=windowWidth,proto3" json:"window_width,omitempty"`
	// WindowHeight is the preferred window height in pixels. If 0, uses default.
	WindowHeight  int32 `protobuf:"varint,11,opt,name=window_height,json=windowHeight,proto3" json:"window_height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebApplication) Reset() {
	*x = WebApplication{}
	mi := &file_proto_yanling_script_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebApplication) ProtoMessage() {}

func (x *WebApplication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebApplication.ProtoReflect.Descriptor instead.
func (*WebApplication) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{2}
}

func (x *WebApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WebApplication) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebApplication) GetBrowserType() string {
	if x != nil {
		return x.BrowserType
	}
	return ""
}

func (x *WebApplication) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebApplication) GetIncognito() bool {
	if x != nil {
		return x.Incognito
	}
	return false
}

func (x *WebApplication) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *WebApplication) GetUserDataDir() string {
	if x != nil {
		return x.UserDataDir
	}
	return ""
}

func (x *WebApplication) GetLoadTimeout() int32 {
	if x != nil {
		return x.LoadTimeout
	}
	return 0
}

func (x *WebApplication) GetWaitTime() int32 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

func (x *WebApplication) GetWindowWidth() int32 {
	if x != nil {
		return x.WindowWidth
	}
	return 0
}

func (x *WebApplication) GetWindowHeight() int32 {
	if x != nil {
		return x.WindowHeight
	}
	return 0
}

// MobileApplication defines mobile application configuration for Android/iOS devices.
type MobileApplication struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id is the unique identifier of the mobile application.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Name is the mobile application name.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Package is the application package name, for example com.example.app.
	Package string `protobuf:"bytes,3,opt,name=package,proto3" json:"package,omitempty"`
	// Activity is the Activity class name to launch, for example .MainActivity.
	// Used with Package to form the component for adb command: adb shell am start -n package/activity.
	Activity string `protobuf:"bytes,4,opt,name=activity,proto3" json:"activity,omitempty"`
	// Action is the Intent action, for example android.intent.action.MAIN or android.intent.action.VIEW.
	// If empty, defaults to android.intent.action.MAIN.
	Action string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	// Flags is the Intent flags as a comma-separated list, for example "FLAG_ACTIVITY_NEW_TASK,FLAG_ACTIVITY_CLEAR_TOP".
	// These are passed to adb with --flags parameter.
	Flags string `protobuf:"bytes,6,opt,name=flags,proto3" json:"flags,omitempty"`
	// Extras is a JSON object containing Intent extras (key-value pairs).
	// For example: {"key1": "value1", "key2": "value2"}.
	Extras string `protobuf:"bytes,7,opt,name=extras,proto3" json:"extras,omitempty"`
	// Timeout is the timeout in milliseconds for starting the application.
	// If 0, no timeout limit is applied.
	Timeout int32 `protobuf:"varint,8,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// WaitTime is the wait time in milliseconds after launching the application before returning.
	// Useful for allowing the app to fully initialize.
	WaitTime      int32 `protobuf:"varint,9,opt,name=wait_time,json=waitTime,proto3" json:"wait_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MobileApplication) Reset() {
	*x = MobileApplication{}
	mi := &file_proto_yanling_script_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MobileApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MobileApplication) ProtoMessage() {}

func (x *MobileApplication) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MobileApplication.ProtoReflect.Descriptor instead.
func (*MobileApplication) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{3}
}

func (x *MobileApplication) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MobileApplication) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MobileApplication) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *MobileApplication) GetActivity() string {
	if x != nil {
		return x.Activity
	}
	return ""
}

func (x *MobileApplication) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MobileApplication) GetFlags() string {
	if x != nil {
		return x.Flags
	}
	return ""
}

func (x *MobileApplication) GetExtras() string {
	if x != nil {
		return x.Extras
	}
	return ""
}

func (x *MobileApplication) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *MobileApplication) GetWaitTime() int32 {
	if x != nil {
		return x.WaitTime
	}
	return 0
}

// ScriptVariable defines script variable configuration.
type ScriptVariable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the variable name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Abstract is the variable description.
	Abstract string `protobuf:"bytes,2,opt,name=abstract,proto3" json:"abstract,omitempty"`
	// Type is the variable type, such as string, integer, boolean, or json.
	Type VariableDataType `protobuf:"varint,3,opt,name=type,proto3,enum=yanlingrpa.protocol.proto.VariableDataType" json:"type,omitempty"`
	// Default is the default value of the variable.
	Default string `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"`
	// Required indicates whether the variable is required.
	Required bool `protobuf:"varint,5,opt,name=required,proto3" json:"required,omitempty"`
	// Save indicates whether to save the variable to project storage.
	Save          bool `protobuf:"varint,6,opt,name=save,proto3" json:"save,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptVariable) Reset() {
	*x = ScriptVariable{}
	mi := &file_proto_yanling_script_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptVariable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptVariable) ProtoMessage() {}

func (x *ScriptVariable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptVariable.ProtoReflect.Descriptor instead.
func (*ScriptVariable) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{4}
}

func (x *ScriptVariable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScriptVariable) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

func (x *ScriptVariable) GetType() VariableDataType {
	if x != nil {
		return x.Type
	}
	return VariableDataType_VARIABLE_DATA_TYPE_UNSPECIFIED
}

func (x *ScriptVariable) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *ScriptVariable) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ScriptVariable) GetSave() bool {
	if x != nil {
		return x.Save
	}
	return false
}

// UrlPermission defines URL-based access permissions.
type UrlPermission struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Url is the URL pattern, supporting wildcard (*) and script variable ${var_name}.
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Permission is the access permission, such as r, w, d, rw, or rwd.
	Permission string `protobuf:"bytes,2,opt,name=permission,proto3" json:"permission,omitempty"`
	// Abstract is the permission description.
	Abstract      string `protobuf:"bytes,3,opt,name=abstract,proto3" json:"abstract,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UrlPermission) Reset() {
	*x = UrlPermission{}
	mi := &file_proto_yanling_script_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UrlPermission) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UrlPermission) ProtoMessage() {}

func (x *UrlPermission) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlPermission.ProtoReflect.Descriptor instead.
func (*UrlPermission) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{5}
}

func (x *UrlPermission) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *UrlPermission) GetPermission() string {
	if x != nil {
		return x.Permission
	}
	return ""
}

func (x *UrlPermission) GetAbstract() string {
	if x != nil {
		return x.Abstract
	}
	return ""
}

// Specifier defines module specification information.
type Specifier struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Domain is the source domain of the module, such as github.com.
	Domain string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	// Owner is the module owner, such as a GitHub username.
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// Name is the module name, such as utils.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Version is the required module version, such as v1.2.3.
	Version       string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Specifier) Reset() {
	*x = Specifier{}
	mi := &file_proto_yanling_script_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Specifier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Specifier) ProtoMessage() {}

func (x *Specifier) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Specifier.ProtoReflect.Descriptor instead.
func (*Specifier) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{6}
}

func (x *Specifier) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Specifier) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *Specifier) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Specifier) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// YScript defines the top-level script configuration structure.
type YScript struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Module is the basic script module information.
	Module *ModuleInfo `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// GuiApps is the list of GUI applications to operate.
	GuiApps []*GuiApplication `protobuf:"bytes,2,rep,name=gui_apps,json=guiApps,proto3" json:"gui_apps,omitempty"`
	// WebApps is the list of web applications to operate.
	WebApps []*WebApplication `protobuf:"bytes,3,rep,name=web_apps,json=webApps,proto3" json:"web_apps,omitempty"`
	// MobileApps is the list of mobile applications to operate.
	MobileApps []*MobileApplication `protobuf:"bytes,4,rep,name=mobile_apps,json=mobileApps,proto3" json:"mobile_apps,omitempty"`
	// Variables is the list of global script variable definitions.
	Variables []*ScriptVariable `protobuf:"bytes,5,rep,name=variables,proto3" json:"variables,omitempty"`
	// FilePermissions is the list of filesystem permissions.
	FilePermissions []*UrlPermission `protobuf:"bytes,6,rep,name=file_permissions,json=filePermissions,proto3" json:"file_permissions,omitempty"`
	// ApiPermissions is the list of network API permissions.
	ApiPermissions []*UrlPermission `protobuf:"bytes,7,rep,name=api_permissions,json=apiPermissions,proto3" json:"api_permissions,omitempty"`
	// ScriptDependencies is the list of script module specifiers imported by this script project.
	ScriptDependencies []string `protobuf:"bytes,8,rep,name=script_dependencies,json=scriptDependencies,proto3" json:"script_dependencies,omitempty"`
	// WorkerDependencies is the list of IPC service dependencies.
	WorkerDependencies []string `protobuf:"bytes,9,rep,name=worker_dependencies,json=workerDependencies,proto3" json:"worker_dependencies,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *YScript) Reset() {
	*x = YScript{}
	mi := &file_proto_yanling_script_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YScript) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YScript) ProtoMessage() {}

func (x *YScript) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yanling_script_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YScript.ProtoReflect.Descriptor instead.
func (*YScript) Descriptor() ([]byte, []int) {
	return file_proto_yanling_script_proto_rawDescGZIP(), []int{7}
}

func (x *YScript) GetModule() *ModuleInfo {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *YScript) GetGuiApps() []*GuiApplication {
	if x != nil {
		return x.GuiApps
	}
	return nil
}

func (x *YScript) GetWebApps() []*WebApplication {
	if x != nil {
		return x.WebApps
	}
	return nil
}

func (x *YScript) GetMobileApps() []*MobileApplication {
	if x != nil {
		return x.MobileApps
	}
	return nil
}

func (x *YScript) GetVariables() []*ScriptVariable {
	if x != nil {
		return x.Variables
	}
	return nil
}

func (x *YScript) GetFilePermissions() []*UrlPermission {
	if x != nil {
		return x.FilePermissions
	}
	return nil
}

func (x *YScript) GetApiPermissions() []*UrlPermission {
	if x != nil {
		return x.ApiPermissions
	}
	return nil
}

func (x *YScript) GetScriptDependencies() []string {
	if x != nil {
		return x.ScriptDependencies
	}
	return nil
}

func (x *YScript) GetWorkerDependencies() []string {
	if x != nil {
		return x.WorkerDependencies
	}
	return nil
}

var File_proto_yanling_script_proto protoreflect.FileDescriptor

const file_proto_yanling_script_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/yanling_script.proto\x12\x19yanlingrpa.protocol.proto\"\xbe\x02\n" +
	"\n" +
	"ModuleInfo\x12\x1c\n" +
	"\tspecifier\x18\x01 \x01(\tR\tspecifier\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\x12\x18\n" +
	"\awebsite\x18\x05 \x01(\tR\awebsite\x12\x1f\n" +
	"\vupdate_time\x18\x06 \x01(\tR\n" +
	"updateTime\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x12\x18\n" +
	"\alicense\x18\t \x01(\tR\alicense\x12\x18\n" +
	"\adevices\x18\n" +
	" \x03(\tR\adevices\x12%\n" +
	"\x0eengine_version\x18\v \x01(\tR\rengineVersion\"\xc9\x02\n" +
	"\x0eGuiApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\blauncher\x18\x03 \x01(\tR\blauncher\x12\x12\n" +
	"\x04args\x18\x04 \x03(\tR\x04args\x12\x19\n" +
	"\bwork_dir\x18\x05 \x01(\tR\aworkDir\x12\x10\n" +
	"\x03env\x18\x06 \x03(\tR\x03env\x12\x18\n" +
	"\aprocess\x18\a \x01(\tR\aprocess\x12\x1d\n" +
	"\n" +
	"launch_uri\x18\b \x01(\tR\tlaunchUri\x12\x18\n" +
	"\atimeout\x18\t \x01(\x05R\atimeout\x12\x1b\n" +
	"\twait_time\x18\n" +
	" \x01(\x05R\bwaitTime\x12!\n" +
	"\fwindow_width\x18\v \x01(\x05R\vwindowWidth\x12#\n" +
	"\rwindow_height\x18\f \x01(\x05R\fwindowHeight\"\xc7\x02\n" +
	"\x0eWebApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\fbrowser_type\x18\x03 \x01(\tR\vbrowserType\x12\x10\n" +
	"\x03url\x18\x04 \x01(\tR\x03url\x12\x1c\n" +
	"\tincognito\x18\x05 \x01(\bR\tincognito\x12\x12\n" +
	"\x04args\x18\x06 \x03(\tR\x04args\x12\"\n" +
	"\ruser_data_dir\x18\a \x01(\tR\vuserDataDir\x12!\n" +
	"\fload_timeout\x18\b \x01(\x05R\vloadTimeout\x12\x1b\n" +
	"\twait_time\x18\t \x01(\x05R\bwaitTime\x12!\n" +
	"\fwindow_width\x18\n" +
	" \x01(\x05R\vwindowWidth\x12#\n" +
	"\rwindow_height\x18\v \x01(\x05R\fwindowHeight\"\xea\x01\n" +
	"\x11MobileApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\apackage\x18\x03 \x01(\tR\apackage\x12\x1a\n" +
	"\bactivity\x18\x04 \x01(\tR\bactivity\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x14\n" +
	"\x05flags\x18\x06 \x01(\tR\x05flags\x12\x16\n" +
	"\x06extras\x18\a \x01(\tR\x06extras\x12\x18\n" +
	"\atimeout\x18\b \x01(\x05R\atimeout\x12\x1b\n" +
	"\twait_time\x18\t \x01(\x05R\bwaitTime\"\xcb\x01\n" +
	"\x0eScriptVariable\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\babstract\x18\x02 \x01(\tR\babstract\x12?\n" +
	"\x04type\x18\x03 \x01(\x0e2+.yanlingrpa.protocol.proto.VariableDataTypeR\x04type\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\x12\x1a\n" +
	"\brequired\x18\x05 \x01(\bR\brequired\x12\x12\n" +
	"\x04save\x18\x06 \x01(\bR\x04save\"]\n" +
	"\rUrlPermission\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"permission\x18\x02 \x01(\tR\n" +
	"permission\x12\x1a\n" +
	"\babstract\x18\x03 \x01(\tR\babstract\"g\n" +
	"\tSpecifier\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x14\n" +
	"\x05owner\x18\x02 \x01(\tR\x05owner\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"\xf6\x04\n" +
	"\aYScript\x12=\n" +
	"\x06module\x18\x01 \x01(\v2%.yanlingrpa.protocol.proto.ModuleInfoR\x06module\x12D\n" +
	"\bgui_apps\x18\x02 \x03(\v2).yanlingrpa.protocol.proto.GuiApplicationR\aguiApps\x12D\n" +
	"\bweb_apps\x18\x03 \x03(\v2).yanlingrpa.protocol.proto.WebApplicationR\awebApps\x12M\n" +
	"\vmobile_apps\x18\x04 \x03(\v2,.yanlingrpa.protocol.proto.MobileApplicationR\n" +
	"mobileApps\x12G\n" +
	"\tvariables\x18\x05 \x03(\v2).yanlingrpa.protocol.proto.ScriptVariableR\tvariables\x12S\n" +
	"\x10file_permissions\x18\x06 \x03(\v2(.yanlingrpa.protocol.proto.UrlPermissionR\x0ffilePermissions\x12Q\n" +
	"\x0fapi_permissions\x18\a \x03(\v2(.yanlingrpa.protocol.proto.UrlPermissionR\x0eapiPermissions\x12/\n" +
	"\x13script_dependencies\x18\b \x03(\tR\x12scriptDependencies\x12/\n" +
	"\x13worker_dependencies\x18\t \x03(\tR\x12workerDependencies*\xb7\x01\n" +
	"\x10VariableDataType\x12\"\n" +
	"\x1eVARIABLE_DATA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VARIABLE_BOOLEAN\x10\x01\x12\x13\n" +
	"\x0fVARIABLE_STRING\x10\x02\x12\x16\n" +
	"\x12VARIABLE_FILE_PATH\x10\x03\x12\x14\n" +
	"\x10VARIABLE_INTEGER\x10\x04\x12\x13\n" +
	"\x0fVARIABLE_NUMBER\x10\x05\x12\x11\n" +
	"\rVARIABLE_JSON\x10\x06B&Z$github.com/yanlingrpa/protocol/protob\x06proto3"

var (
	file_proto_yanling_script_proto_rawDescOnce sync.Once
	file_proto_yanling_script_proto_rawDescData []byte
)

func file_proto_yanling_script_proto_rawDescGZIP() []byte {
	file_proto_yanling_script_proto_rawDescOnce.Do(func() {
		file_proto_yanling_script_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_yanling_script_proto_rawDesc), len(file_proto_yanling_script_proto_rawDesc)))
	})
	return file_proto_yanling_script_proto_rawDescData
}

var file_proto_yanling_script_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_yanling_script_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_yanling_script_proto_goTypes = []any{
	(VariableDataType)(0),     // 0: yanlingrpa.protocol.proto.VariableDataType
	(*ModuleInfo)(nil),        // 1: yanlingrpa.protocol.proto.ModuleInfo
	(*GuiApplication)(nil),    // 2: yanlingrpa.protocol.proto.GuiApplication
	(*WebApplication)(nil),    // 3: yanlingrpa.protocol.proto.WebApplication
	(*MobileApplication)(nil), // 4: yanlingrpa.protocol.proto.MobileApplication
	(*ScriptVariable)(nil),    // 5: yanlingrpa.protocol.proto.ScriptVariable
	(*UrlPermission)(nil),     // 6: yanlingrpa.protocol.proto.UrlPermission
	(*Specifier)(nil),         // 7: yanlingrpa.protocol.proto.Specifier
	(*YScript)(nil),           // 8: yanlingrpa.protocol.proto.YScript
}
var file_proto_yanling_script_proto_depIdxs = []int32{
	0, // 0: yanlingrpa.protocol.proto.ScriptVariable.type:type_name -> yanlingrpa.protocol.proto.VariableDataType
	1, // 1: yanlingrpa.protocol.proto.YScript.module:type_name -> yanlingrpa.protocol.proto.ModuleInfo
	2, // 2: yanlingrpa.protocol.proto.YScript.gui_apps:type_name -> yanlingrpa.protocol.proto.GuiApplication
	3, // 3: yanlingrpa.protocol.proto.YScript.web_apps:type_name -> yanlingrpa.protocol.proto.WebApplication
	4, // 4: yanlingrpa.protocol.proto.YScript.mobile_apps:type_name -> yanlingrpa.protocol.proto.MobileApplication
	5, // 5: yanlingrpa.protocol.proto.YScript.variables:type_name -> yanlingrpa.protocol.proto.ScriptVariable
	6, // 6: yanlingrpa.protocol.proto.YScript.file_permissions:type_name -> yanlingrpa.protocol.proto.UrlPermission
	6, // 7: yanlingrpa.protocol.proto.YScript.api_permissions:type_name -> yanlingrpa.protocol.proto.UrlPermission
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_yanling_script_proto_init() }
func file_proto_yanling_script_proto_init() {
	if File_proto_yanling_script_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yanling_script_proto_rawDesc), len(file_proto_yanling_script_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_yanling_script_proto_goTypes,
		DependencyIndexes: file_proto_yanling_script_proto_depIdxs,
		EnumInfos:         file_proto_yanling_script_proto_enumTypes,
		MessageInfos:      file_proto_yanling_script_proto_msgTypes,
	}.Build()
	File_proto_yanling_script_proto = out.File
	file_proto_yanling_script_proto_goTypes = nil
	file_proto_yanling_script_proto_depIdxs = nil
}
